// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Foundation.Alerting.Database;

public partial class AlertingContext : DbContext
{
    public AlertingContext(DbContextOptions<AlertingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<EscalationPolicy> EscalationPolicies { get; set; }

    public virtual DbSet<EscalationPolicyChangeHistory> EscalationPolicyChangeHistories { get; set; }

    public virtual DbSet<EscalationRule> EscalationRules { get; set; }

    public virtual DbSet<EscalationRuleChangeHistory> EscalationRuleChangeHistories { get; set; }

    public virtual DbSet<Incident> Incidents { get; set; }

    public virtual DbSet<IncidentChangeHistory> IncidentChangeHistories { get; set; }

    public virtual DbSet<IncidentEventType> IncidentEventTypes { get; set; }

    public virtual DbSet<IncidentNote> IncidentNotes { get; set; }

    public virtual DbSet<IncidentNoteChangeHistory> IncidentNoteChangeHistories { get; set; }

    public virtual DbSet<IncidentNotification> IncidentNotifications { get; set; }

    public virtual DbSet<IncidentStatusType> IncidentStatusTypes { get; set; }

    public virtual DbSet<IncidentTimelineEvent> IncidentTimelineEvents { get; set; }

    public virtual DbSet<Integration> Integrations { get; set; }

    public virtual DbSet<IntegrationCallbackIncidentEventType> IntegrationCallbackIncidentEventTypes { get; set; }

    public virtual DbSet<IntegrationCallbackIncidentEventTypeChangeHistory> IntegrationCallbackIncidentEventTypeChangeHistories { get; set; }

    public virtual DbSet<IntegrationChangeHistory> IntegrationChangeHistories { get; set; }

    public virtual DbSet<NotificationChannelType> NotificationChannelTypes { get; set; }

    public virtual DbSet<NotificationDeliveryAttempt> NotificationDeliveryAttempts { get; set; }

    public virtual DbSet<OnCallSchedule> OnCallSchedules { get; set; }

    public virtual DbSet<OnCallScheduleChangeHistory> OnCallScheduleChangeHistories { get; set; }

    public virtual DbSet<ScheduleLayer> ScheduleLayers { get; set; }

    public virtual DbSet<ScheduleLayerChangeHistory> ScheduleLayerChangeHistories { get; set; }

    public virtual DbSet<ScheduleLayerMember> ScheduleLayerMembers { get; set; }

    public virtual DbSet<ScheduleLayerMemberChangeHistory> ScheduleLayerMemberChangeHistories { get; set; }

    public virtual DbSet<ScheduleOverride> ScheduleOverrides { get; set; }

    public virtual DbSet<ScheduleOverrideChangeHistory> ScheduleOverrideChangeHistories { get; set; }

    public virtual DbSet<ScheduleOverrideType> ScheduleOverrideTypes { get; set; }

    public virtual DbSet<Service> Services { get; set; }

    public virtual DbSet<ServiceChangeHistory> ServiceChangeHistories { get; set; }

    public virtual DbSet<SeverityType> SeverityTypes { get; set; }

    public virtual DbSet<UserNotificationChannelPreference> UserNotificationChannelPreferences { get; set; }

    public virtual DbSet<UserNotificationChannelPreferenceChangeHistory> UserNotificationChannelPreferenceChangeHistories { get; set; }

    public virtual DbSet<UserNotificationPreference> UserNotificationPreferences { get; set; }

    public virtual DbSet<UserNotificationPreferenceChangeHistory> UserNotificationPreferenceChangeHistories { get; set; }

    public virtual DbSet<UserPushToken> UserPushTokens { get; set; }

    public virtual DbSet<UserPushTokenChangeHistory> UserPushTokenChangeHistories { get; set; }

    public virtual DbSet<WebhookDeliveryAttempt> WebhookDeliveryAttempts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<EscalationPolicy>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Escalati__3213E83FBEBD21AD");

            entity.ToTable("EscalationPolicy", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_EscalationPolicy_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_EscalationPolicy_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_EscalationPolicy_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "I_EscalationPolicy_tenantGuid_name");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "UC_EscalationPolicy_tenantGuid_name").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__Escalati__3E543F94B5C6D896").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);
        });

        modelBuilder.Entity<EscalationPolicyChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Escalati__3213E83FBE1B94FD");

            entity.ToTable("EscalationPolicyChangeHistory", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_EscalationPolicyChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.escalationPolicyId }, "I_EscalationPolicyChangeHistory_tenantGuid_escalationPolicyId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_EscalationPolicyChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_EscalationPolicyChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_EscalationPolicyChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.escalationPolicy).WithMany(p => p.EscalationPolicyChangeHistories)
                .HasForeignKey(d => d.escalationPolicyId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<EscalationRule>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Escalati__3213E83F42F0A77C");

            entity.ToTable("EscalationRule", "Alerting");

            entity.HasIndex(e => new { e.escalationPolicyId, e.ruleOrder }, "I_EscalationRule_escalationPolicyId_ruleOrder");

            entity.HasIndex(e => e.tenantGuid, "I_EscalationRule_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_EscalationRule_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_EscalationRule_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.escalationPolicyId }, "I_EscalationRule_tenantGuid_escalationPolicyId");

            entity.HasIndex(e => new { e.tenantGuid, e.ruleOrder }, "I_EscalationRule_tenantGuid_ruleOrder");

            entity.HasIndex(e => e.objectGuid, "UQ__Escalati__3E543F941E7B0080").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.targetType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.escalationPolicy).WithMany(p => p.EscalationRules)
                .HasForeignKey(d => d.escalationPolicyId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<EscalationRuleChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Escalati__3213E83F5777B3E7");

            entity.ToTable("EscalationRuleChangeHistory", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_EscalationRuleChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.escalationRuleId }, "I_EscalationRuleChangeHistory_tenantGuid_escalationRuleId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_EscalationRuleChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_EscalationRuleChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_EscalationRuleChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.escalationRule).WithMany(p => p.EscalationRuleChangeHistories)
                .HasForeignKey(d => d.escalationRuleId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Incident>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Incident__3213E83F9B74C89D");

            entity.ToTable("Incident", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_Incident_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_Incident_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.createdAt }, "I_Incident_tenantGuid_createdAt");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_Incident_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.escalationRuleId }, "I_Incident_tenantGuid_escalationRuleId");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentKey }, "I_Incident_tenantGuid_incidentKey");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentStatusTypeId }, "I_Incident_tenantGuid_incidentStatusTypeId");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentStatusTypeId, e.createdAt }, "I_Incident_tenantGuid_incidentStatusTypeId_createdAt");

            entity.HasIndex(e => new { e.tenantGuid, e.nextEscalationAt, e.incidentStatusTypeId }, "I_Incident_tenantGuid_nextEscalationAt_incidentStatusTypeId");

            entity.HasIndex(e => new { e.tenantGuid, e.serviceId }, "I_Incident_tenantGuid_serviceId");

            entity.HasIndex(e => new { e.tenantGuid, e.serviceId, e.createdAt }, "I_Incident_tenantGuid_serviceId_createdAt");

            entity.HasIndex(e => new { e.tenantGuid, e.severityTypeId }, "I_Incident_tenantGuid_severityTypeId");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentKey }, "UC_Incident_tenantGuid_incidentKey").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__Incident__3E543F949647C1BB").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.currentRepeatCount).HasDefaultValue(0);
            entity.Property(e => e.incidentKey)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.title)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.escalationRule).WithMany(p => p.Incidents).HasForeignKey(d => d.escalationRuleId);

            entity.HasOne(d => d.incidentStatusType).WithMany(p => p.Incidents)
                .HasForeignKey(d => d.incidentStatusTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.service).WithMany(p => p.Incidents)
                .HasForeignKey(d => d.serviceId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.severityType).WithMany(p => p.Incidents)
                .HasForeignKey(d => d.severityTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<IncidentChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Incident__3213E83FA24D514B");

            entity.ToTable("IncidentChangeHistory", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_IncidentChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentId }, "I_IncidentChangeHistory_tenantGuid_incidentId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_IncidentChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_IncidentChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_IncidentChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.incident).WithMany(p => p.IncidentChangeHistories)
                .HasForeignKey(d => d.incidentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<IncidentEventType>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Incident__3213E83FE1C401EF");

            entity.ToTable("IncidentEventType", "Alerting");

            entity.HasIndex(e => e.active, "I_IncidentEventType_active");

            entity.HasIndex(e => e.deleted, "I_IncidentEventType_deleted");

            entity.HasIndex(e => e.name, "I_IncidentEventType_name");

            entity.HasIndex(e => e.name, "UQ__Incident__72E12F1B63160075").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<IncidentNote>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Incident__3213E83F67D921A9");

            entity.ToTable("IncidentNote", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_IncidentNote_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_IncidentNote_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_IncidentNote_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentId }, "I_IncidentNote_tenantGuid_incidentId");

            entity.HasIndex(e => e.objectGuid, "UQ__Incident__3E543F942CC9DF22").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.content).IsRequired();
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.incident).WithMany(p => p.IncidentNotes)
                .HasForeignKey(d => d.incidentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<IncidentNoteChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Incident__3213E83F79D265D3");

            entity.ToTable("IncidentNoteChangeHistory", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_IncidentNoteChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentNoteId }, "I_IncidentNoteChangeHistory_tenantGuid_incidentNoteId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_IncidentNoteChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_IncidentNoteChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_IncidentNoteChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.incidentNote).WithMany(p => p.IncidentNoteChangeHistories)
                .HasForeignKey(d => d.incidentNoteId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<IncidentNotification>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Incident__3213E83FCD86E5D9");

            entity.ToTable("IncidentNotification", "Alerting");

            entity.HasIndex(e => new { e.incidentId, e.userObjectGuid }, "I_IncidentNotification_incidentId_userObjectGuid");

            entity.HasIndex(e => e.tenantGuid, "I_IncidentNotification_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_IncidentNotification_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_IncidentNotification_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.escalationRuleId }, "I_IncidentNotification_tenantGuid_escalationRuleId");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentId }, "I_IncidentNotification_tenantGuid_incidentId");

            entity.HasIndex(e => e.objectGuid, "UQ__Incident__3E543F94DC8A5B74").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);

            entity.HasOne(d => d.escalationRule).WithMany(p => p.IncidentNotifications).HasForeignKey(d => d.escalationRuleId);

            entity.HasOne(d => d.incident).WithMany(p => p.IncidentNotifications)
                .HasForeignKey(d => d.incidentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<IncidentStatusType>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Incident__3213E83FED676401");

            entity.ToTable("IncidentStatusType", "Alerting");

            entity.HasIndex(e => e.active, "I_IncidentStatusType_active");

            entity.HasIndex(e => e.deleted, "I_IncidentStatusType_deleted");

            entity.HasIndex(e => e.name, "I_IncidentStatusType_name");

            entity.HasIndex(e => e.name, "UQ__Incident__72E12F1B52A76EFD").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<IncidentTimelineEvent>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Incident__3213E83F8FB1BBDA");

            entity.ToTable("IncidentTimelineEvent", "Alerting");

            entity.HasIndex(e => new { e.incidentId, e.timestamp }, "I_IncidentTimelineEvent_incidentId_timestamp");

            entity.HasIndex(e => e.tenantGuid, "I_IncidentTimelineEvent_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_IncidentTimelineEvent_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_IncidentTimelineEvent_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentEventTypeId }, "I_IncidentTimelineEvent_tenantGuid_incidentEventTypeId");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentId }, "I_IncidentTimelineEvent_tenantGuid_incidentId");

            entity.HasIndex(e => new { e.tenantGuid, e.timestamp }, "I_IncidentTimelineEvent_tenantGuid_timestamp");

            entity.HasIndex(e => e.objectGuid, "UQ__Incident__3E543F9481BFEC2D").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);

            entity.HasOne(d => d.incidentEventType).WithMany(p => p.IncidentTimelineEvents)
                .HasForeignKey(d => d.incidentEventTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.incident).WithMany(p => p.IncidentTimelineEvents)
                .HasForeignKey(d => d.incidentId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Integration>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Integrat__3213E83F928176CF");

            entity.ToTable("Integration", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_Integration_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_Integration_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_Integration_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "I_Integration_tenantGuid_name");

            entity.HasIndex(e => new { e.tenantGuid, e.serviceId }, "I_Integration_tenantGuid_serviceId");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "UC_Integration_tenantGuid_name").IsUnique();

            entity.HasIndex(e => e.apiKeyHash, "UQ__Integrat__0295CF696E196C50").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__Integrat__3E543F94CA4F205D").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.apiKeyHash)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.callbackWebhookUrl).HasMaxLength(1000);
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.maxRetryAttempts).HasDefaultValue(10);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.retryBackoffSeconds).HasDefaultValue(30);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.service).WithMany(p => p.Integrations)
                .HasForeignKey(d => d.serviceId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<IntegrationCallbackIncidentEventType>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Integrat__3213E83F059444A2");

            entity.ToTable("IntegrationCallbackIncidentEventType", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_IntegrationCallbackIncidentEventType_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_IntegrationCallbackIncidentEventType_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_IntegrationCallbackIncidentEventType_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentEventTypeId }, "I_IntegrationCallbackIncidentEventType_tenantGuid_incidentEventTypeId");

            entity.HasIndex(e => new { e.tenantGuid, e.integrationId }, "I_IntegrationCallbackIncidentEventType_tenantGuid_integrationId");

            entity.HasIndex(e => e.objectGuid, "UQ__Integrat__3E543F94DA7DE7E7").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.incidentEventType).WithMany(p => p.IntegrationCallbackIncidentEventTypes)
                .HasForeignKey(d => d.incidentEventTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.integration).WithMany(p => p.IntegrationCallbackIncidentEventTypes)
                .HasForeignKey(d => d.integrationId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<IntegrationCallbackIncidentEventTypeChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Integrat__3213E83FC4F8565E");

            entity.ToTable("IntegrationCallbackIncidentEventTypeChangeHistory", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_IntegrationCallbackIncidentEventTypeChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.integrationCallbackIncidentEventTypeId }, "I_IntegrationCallbackIncidentEventTypeChangeHistory_tenantGuid_integrationCallbackIncidentEventTypeId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_IntegrationCallbackIncidentEventTypeChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_IntegrationCallbackIncidentEventTypeChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_IntegrationCallbackIncidentEventTypeChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.integrationCallbackIncidentEventType).WithMany(p => p.IntegrationCallbackIncidentEventTypeChangeHistories)
                .HasForeignKey(d => d.integrationCallbackIncidentEventTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<IntegrationChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Integrat__3213E83FAAD0BD2B");

            entity.ToTable("IntegrationChangeHistory", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_IntegrationChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.integrationId }, "I_IntegrationChangeHistory_tenantGuid_integrationId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_IntegrationChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_IntegrationChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_IntegrationChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.integration).WithMany(p => p.IntegrationChangeHistories)
                .HasForeignKey(d => d.integrationId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<NotificationChannelType>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Notifica__3213E83FDEB080CC");

            entity.ToTable("NotificationChannelType", "Alerting");

            entity.HasIndex(e => e.active, "I_NotificationChannelType_active");

            entity.HasIndex(e => e.deleted, "I_NotificationChannelType_deleted");

            entity.HasIndex(e => e.name, "I_NotificationChannelType_name");

            entity.HasIndex(e => e.name, "UQ__Notifica__72E12F1BC1B5597B").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<NotificationDeliveryAttempt>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Notifica__3213E83FEFFBF7BC");

            entity.ToTable("NotificationDeliveryAttempt", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_NotificationDeliveryAttempt_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_NotificationDeliveryAttempt_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_NotificationDeliveryAttempt_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentNotificationId }, "I_NotificationDeliveryAttempt_tenantGuid_incidentNotificationId");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentNotificationId, e.notificationChannelTypeId }, "I_NotificationDeliveryAttempt_tenantGuid_incidentNotificationId_notificationChannelTypeId");

            entity.HasIndex(e => new { e.tenantGuid, e.notificationChannelTypeId }, "I_NotificationDeliveryAttempt_tenantGuid_notificationChannelTypeId");

            entity.HasIndex(e => e.objectGuid, "UQ__Notifica__3E543F9403F74A70").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.attemptNumber).HasDefaultValue(1);
            entity.Property(e => e.status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Pending");

            entity.HasOne(d => d.incidentNotification).WithMany(p => p.NotificationDeliveryAttempts)
                .HasForeignKey(d => d.incidentNotificationId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.notificationChannelType).WithMany(p => p.NotificationDeliveryAttempts)
                .HasForeignKey(d => d.notificationChannelTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<OnCallSchedule>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__OnCallSc__3213E83F47D5BB96");

            entity.ToTable("OnCallSchedule", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_OnCallSchedule_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_OnCallSchedule_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_OnCallSchedule_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "I_OnCallSchedule_tenantGuid_name");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "UC_OnCallSchedule_tenantGuid_name").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__OnCallSc__3E543F94B86C6BDA").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.timeZoneId)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("UTC");
            entity.Property(e => e.versionNumber).HasDefaultValue(1);
        });

        modelBuilder.Entity<OnCallScheduleChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__OnCallSc__3213E83F34DE1DE5");

            entity.ToTable("OnCallScheduleChangeHistory", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_OnCallScheduleChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.onCallScheduleId }, "I_OnCallScheduleChangeHistory_tenantGuid_onCallScheduleId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_OnCallScheduleChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_OnCallScheduleChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_OnCallScheduleChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.onCallSchedule).WithMany(p => p.OnCallScheduleChangeHistories)
                .HasForeignKey(d => d.onCallScheduleId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ScheduleLayer>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Schedule__3213E83FBD1B5703");

            entity.ToTable("ScheduleLayer", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_ScheduleLayer_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_ScheduleLayer_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_ScheduleLayer_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "I_ScheduleLayer_tenantGuid_name");

            entity.HasIndex(e => new { e.tenantGuid, e.onCallScheduleId }, "I_ScheduleLayer_tenantGuid_onCallScheduleId");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "UC_ScheduleLayer_tenantGuid_name").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__Schedule__3E543F940192886A").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.handoffTime)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("09:00");
            entity.Property(e => e.layerLevel).HasDefaultValue(1);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.rotationDays).HasDefaultValue(7);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.onCallSchedule).WithMany(p => p.ScheduleLayers)
                .HasForeignKey(d => d.onCallScheduleId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ScheduleLayerChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Schedule__3213E83F75CBA09F");

            entity.ToTable("ScheduleLayerChangeHistory", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_ScheduleLayerChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.scheduleLayerId }, "I_ScheduleLayerChangeHistory_tenantGuid_scheduleLayerId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_ScheduleLayerChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_ScheduleLayerChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_ScheduleLayerChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.scheduleLayer).WithMany(p => p.ScheduleLayerChangeHistories)
                .HasForeignKey(d => d.scheduleLayerId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ScheduleLayerMember>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Schedule__3213E83F6ED8E0B1");

            entity.ToTable("ScheduleLayerMember", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_ScheduleLayerMember_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_ScheduleLayerMember_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_ScheduleLayerMember_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.scheduleLayerId }, "I_ScheduleLayerMember_tenantGuid_scheduleLayerId");

            entity.HasIndex(e => new { e.tenantGuid, e.scheduleLayerId, e.position }, "UC_ScheduleLayerMember_tenantGuid_scheduleLayerId_position").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__Schedule__3E543F945BD296E8").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.scheduleLayer).WithMany(p => p.ScheduleLayerMembers)
                .HasForeignKey(d => d.scheduleLayerId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ScheduleLayerMemberChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Schedule__3213E83F5EF83E3F");

            entity.ToTable("ScheduleLayerMemberChangeHistory", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_ScheduleLayerMemberChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.scheduleLayerMemberId }, "I_ScheduleLayerMemberChangeHistory_tenantGuid_scheduleLayerMemberId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_ScheduleLayerMemberChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_ScheduleLayerMemberChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_ScheduleLayerMemberChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.scheduleLayerMember).WithMany(p => p.ScheduleLayerMemberChangeHistories)
                .HasForeignKey(d => d.scheduleLayerMemberId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ScheduleOverride>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Schedule__3213E83FC524AE7F");

            entity.ToTable("ScheduleOverride", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_ScheduleOverride_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_ScheduleOverride_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_ScheduleOverride_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.onCallScheduleId }, "I_ScheduleOverride_tenantGuid_onCallScheduleId");

            entity.HasIndex(e => new { e.tenantGuid, e.onCallScheduleId, e.startDateTime, e.endDateTime }, "I_ScheduleOverride_tenantGuid_onCallScheduleId_startDateTime_endDateTime");

            entity.HasIndex(e => new { e.tenantGuid, e.originalUserObjectGuid }, "I_ScheduleOverride_tenantGuid_originalUserObjectGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.scheduleLayerId }, "I_ScheduleOverride_tenantGuid_scheduleLayerId");

            entity.HasIndex(e => new { e.tenantGuid, e.scheduleOverrideTypeId }, "I_ScheduleOverride_tenantGuid_scheduleOverrideTypeId");

            entity.HasIndex(e => e.objectGuid, "UQ__Schedule__3E543F94F98171AD").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.reason).HasMaxLength(500);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.onCallSchedule).WithMany(p => p.ScheduleOverrides)
                .HasForeignKey(d => d.onCallScheduleId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.scheduleLayer).WithMany(p => p.ScheduleOverrides).HasForeignKey(d => d.scheduleLayerId);

            entity.HasOne(d => d.scheduleOverrideType).WithMany(p => p.ScheduleOverrides)
                .HasForeignKey(d => d.scheduleOverrideTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ScheduleOverrideChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Schedule__3213E83FA2CEA8B6");

            entity.ToTable("ScheduleOverrideChangeHistory", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_ScheduleOverrideChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.scheduleOverrideId }, "I_ScheduleOverrideChangeHistory_tenantGuid_scheduleOverrideId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_ScheduleOverrideChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_ScheduleOverrideChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_ScheduleOverrideChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.scheduleOverride).WithMany(p => p.ScheduleOverrideChangeHistories)
                .HasForeignKey(d => d.scheduleOverrideId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ScheduleOverrideType>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Schedule__3213E83F4F2114B2");

            entity.ToTable("ScheduleOverrideType", "Alerting");

            entity.HasIndex(e => e.active, "I_ScheduleOverrideType_active");

            entity.HasIndex(e => e.deleted, "I_ScheduleOverrideType_deleted");

            entity.HasIndex(e => e.name, "I_ScheduleOverrideType_name");

            entity.HasIndex(e => e.name, "UQ__Schedule__72E12F1B40BFBE04").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Service>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Service__3213E83FC83DD1A0");

            entity.ToTable("Service", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_Service_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_Service_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_Service_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.escalationPolicyId }, "I_Service_tenantGuid_escalationPolicyId");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "I_Service_tenantGuid_name");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "UC_Service_tenantGuid_name").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__Service__3E543F94B58DD745").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.escalationPolicy).WithMany(p => p.Services).HasForeignKey(d => d.escalationPolicyId);
        });

        modelBuilder.Entity<ServiceChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__ServiceC__3213E83F9C6437CA");

            entity.ToTable("ServiceChangeHistory", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_ServiceChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.serviceId }, "I_ServiceChangeHistory_tenantGuid_serviceId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_ServiceChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_ServiceChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_ServiceChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.service).WithMany(p => p.ServiceChangeHistories)
                .HasForeignKey(d => d.serviceId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<SeverityType>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Severity__3213E83F37579287");

            entity.ToTable("SeverityType", "Alerting");

            entity.HasIndex(e => e.active, "I_SeverityType_active");

            entity.HasIndex(e => e.deleted, "I_SeverityType_deleted");

            entity.HasIndex(e => e.name, "I_SeverityType_name");

            entity.HasIndex(e => e.name, "UQ__Severity__72E12F1B8EC79F60").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<UserNotificationChannelPreference>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__UserNoti__3213E83F01F2EEBF");

            entity.ToTable("UserNotificationChannelPreference", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_UserNotificationChannelPreference_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_UserNotificationChannelPreference_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_UserNotificationChannelPreference_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.notificationChannelTypeId }, "I_UserNotificationChannelPreference_tenantGuid_notificationChannelTypeId");

            entity.HasIndex(e => new { e.tenantGuid, e.userNotificationPreferenceId }, "I_UserNotificationChannelPreference_tenantGuid_userNotificationPreferenceId");

            entity.HasIndex(e => new { e.tenantGuid, e.userNotificationPreferenceId, e.notificationChannelTypeId }, "UC_UserNotificationChannelPreference_tenantGuid_userNotificationPreferenceId_notificationChannelTypeId").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__UserNoti__3E543F941BB0413D").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.isEnabled).HasDefaultValue(true);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.notificationChannelType).WithMany(p => p.UserNotificationChannelPreferences)
                .HasForeignKey(d => d.notificationChannelTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.userNotificationPreference).WithMany(p => p.UserNotificationChannelPreferences)
                .HasForeignKey(d => d.userNotificationPreferenceId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<UserNotificationChannelPreferenceChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__UserNoti__3213E83FB3301A7E");

            entity.ToTable("UserNotificationChannelPreferenceChangeHistory", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_UserNotificationChannelPreferenceChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_UserNotificationChannelPreferenceChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_UserNotificationChannelPreferenceChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.userNotificationChannelPreferenceId }, "I_UserNotificationChannelPreferenceChangeHistory_tenantGuid_userNotificationChannelPreferenceId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_UserNotificationChannelPreferenceChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.userNotificationChannelPreference).WithMany(p => p.UserNotificationChannelPreferenceChangeHistories)
                .HasForeignKey(d => d.userNotificationChannelPreferenceId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<UserNotificationPreference>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__UserNoti__3213E83F23CE780B");

            entity.ToTable("UserNotificationPreference", "Alerting");

            entity.HasIndex(e => e.securityUserObjectGuid, "I_UserNotificationPreference_securityUserObjectGuid");

            entity.HasIndex(e => e.tenantGuid, "I_UserNotificationPreference_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_UserNotificationPreference_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_UserNotificationPreference_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.securityUserObjectGuid, e.active, e.deleted }, "UC_UserNotificationPreference_tenantGuid_securityUserObjectGuid_active_deleted").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__UserNoti__3E543F94428DA801").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.quietHoursEnd).HasMaxLength(10);
            entity.Property(e => e.quietHoursStart).HasMaxLength(10);
            entity.Property(e => e.timeZoneId)
                .HasMaxLength(50)
                .HasDefaultValue("UTC");
            entity.Property(e => e.versionNumber).HasDefaultValue(1);
        });

        modelBuilder.Entity<UserNotificationPreferenceChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__UserNoti__3213E83F3A8AA330");

            entity.ToTable("UserNotificationPreferenceChangeHistory", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_UserNotificationPreferenceChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_UserNotificationPreferenceChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_UserNotificationPreferenceChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.userNotificationPreferenceId }, "I_UserNotificationPreferenceChangeHistory_tenantGuid_userNotificationPreferenceId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_UserNotificationPreferenceChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.userNotificationPreference).WithMany(p => p.UserNotificationPreferenceChangeHistories)
                .HasForeignKey(d => d.userNotificationPreferenceId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<UserPushToken>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__UserPush__3213E83F27404544");

            entity.ToTable("UserPushToken", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_UserPushToken_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_UserPushToken_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_UserPushToken_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.userObjectGuid }, "I_UserPushToken_tenantGuid_userObjectGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.userObjectGuid, e.deviceFingerprint }, "UC_UserPushToken_tenantGuid_userObjectGuid_deviceFingerprint").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__UserPush__3E543F9497B89AB5").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.deviceFingerprint)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.fcmToken)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.platform)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("web");
            entity.Property(e => e.userAgent).HasMaxLength(500);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);
        });

        modelBuilder.Entity<UserPushTokenChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__UserPush__3213E83F362B2023");

            entity.ToTable("UserPushTokenChangeHistory", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_UserPushTokenChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_UserPushTokenChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_UserPushTokenChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.userPushTokenId }, "I_UserPushTokenChangeHistory_tenantGuid_userPushTokenId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_UserPushTokenChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.userPushToken).WithMany(p => p.UserPushTokenChangeHistories)
                .HasForeignKey(d => d.userPushTokenId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<WebhookDeliveryAttempt>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__WebhookD__3213E83FDBEC8E71");

            entity.ToTable("WebhookDeliveryAttempt", "Alerting");

            entity.HasIndex(e => e.tenantGuid, "I_WebhookDeliveryAttempt_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_WebhookDeliveryAttempt_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_WebhookDeliveryAttempt_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentId }, "I_WebhookDeliveryAttempt_tenantGuid_incidentId");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentId, e.attemptedAt }, "I_WebhookDeliveryAttempt_tenantGuid_incidentId_attemptedAt");

            entity.HasIndex(e => new { e.tenantGuid, e.incidentTimelineEventId }, "I_WebhookDeliveryAttempt_tenantGuid_incidentTimelineEventId");

            entity.HasIndex(e => new { e.tenantGuid, e.integrationId }, "I_WebhookDeliveryAttempt_tenantGuid_integrationId");

            entity.HasIndex(e => e.objectGuid, "UQ__WebhookD__3E543F94CE3DFA90").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.attemptNumber).HasDefaultValue(1);

            entity.HasOne(d => d.incident).WithMany(p => p.WebhookDeliveryAttempts)
                .HasForeignKey(d => d.incidentId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.incidentTimelineEvent).WithMany(p => p.WebhookDeliveryAttempts).HasForeignKey(d => d.incidentTimelineEventId);

            entity.HasOne(d => d.integration).WithMany(p => p.WebhookDeliveryAttempts)
                .HasForeignKey(d => d.integrationId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}