// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Alerting.Database;

public partial class Incident
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string incidentKey { get; set; }

    public int serviceId { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public int severityTypeId { get; set; }

    public int incidentStatusTypeId { get; set; }

    public DateTime createdAt { get; set; }

    public int? escalationRuleId { get; set; }

    public int? currentRepeatCount { get; set; }

    public DateTime? nextEscalationAt { get; set; }

    public DateTime? acknowledgedAt { get; set; }

    public DateTime? resolvedAt { get; set; }

    public Guid? currentAssigneeObjectGuid { get; set; }

    public string sourcePayloadJson { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<IncidentChangeHistory> IncidentChangeHistories { get; set; } = new List<IncidentChangeHistory>();

    public virtual ICollection<IncidentNote> IncidentNotes { get; set; } = new List<IncidentNote>();

    public virtual ICollection<IncidentNotification> IncidentNotifications { get; set; } = new List<IncidentNotification>();

    public virtual ICollection<IncidentTimelineEvent> IncidentTimelineEvents { get; set; } = new List<IncidentTimelineEvent>();

    public virtual ICollection<WebhookDeliveryAttempt> WebhookDeliveryAttempts { get; set; } = new List<WebhookDeliveryAttempt>();

    public virtual EscalationRule escalationRule { get; set; }

    public virtual IncidentStatusType incidentStatusType { get; set; }

    public virtual Service service { get; set; }

    public virtual SeverityType severityType { get; set; }
}