// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Alerting.Database;

public partial class IncidentNote
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int incidentId { get; set; }

    public Guid authorObjectGuid { get; set; }

    public DateTime createdAt { get; set; }

    public string content { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<IncidentNoteChangeHistory> IncidentNoteChangeHistories { get; set; } = new List<IncidentNoteChangeHistory>();

    public virtual Incident incident { get; set; }
}