// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Alerting.Database;

public partial class NotificationDeliveryAttempt
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int incidentNotificationId { get; set; }

    public int notificationChannelTypeId { get; set; }

    public int attemptNumber { get; set; }

    public DateTime attemptedAt { get; set; }

    public string status { get; set; }

    public string errorMessage { get; set; }

    public string response { get; set; }

    public string recipientAddress { get; set; }

    public string subject { get; set; }

    public string bodyContent { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual IncidentNotification incidentNotification { get; set; }

    public virtual NotificationChannelType notificationChannelType { get; set; }
}