// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Alerting.Database;

public partial class ScheduleOverride
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int onCallScheduleId { get; set; }

    public int? scheduleLayerId { get; set; }

    public DateTime startDateTime { get; set; }

    public DateTime endDateTime { get; set; }

    public int scheduleOverrideTypeId { get; set; }

    public Guid? originalUserObjectGuid { get; set; }

    public Guid? replacementUserObjectGuid { get; set; }

    public string reason { get; set; }

    public Guid createdByUserObjectGuid { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<ScheduleOverrideChangeHistory> ScheduleOverrideChangeHistories { get; set; } = new List<ScheduleOverrideChangeHistory>();

    public virtual OnCallSchedule onCallSchedule { get; set; }

    public virtual ScheduleLayer scheduleLayer { get; set; }

    public virtual ScheduleOverrideType scheduleOverrideType { get; set; }
}