// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Alerting.Database;

public partial class ScheduleLayerMember
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int scheduleLayerId { get; set; }

    public int position { get; set; }

    public Guid securityUserObjectGuid { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<ScheduleLayerMemberChangeHistory> ScheduleLayerMemberChangeHistories { get; set; } = new List<ScheduleLayerMemberChangeHistory>();

    public virtual ScheduleLayer scheduleLayer { get; set; }
}