// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Alerting.Database;

public partial class WebhookDeliveryAttempt
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int incidentId { get; set; }

    public int integrationId { get; set; }

    public int? incidentTimelineEventId { get; set; }

    public int attemptNumber { get; set; }

    public DateTime attemptedAt { get; set; }

    public int? httpStatusCode { get; set; }

    public bool success { get; set; }

    public string payloadJson { get; set; }

    public string responseBody { get; set; }

    public string errorMessage { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual Incident incident { get; set; }

    public virtual IncidentTimelineEvent incidentTimelineEvent { get; set; }

    public virtual Integration integration { get; set; }
}