// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.DeepSpace.Database;

public partial class AccessLog
{
    public int id { get; set; }

    public int storageObjectId { get; set; }

    public int accessTypeId { get; set; }

    public Guid? accessedByUserGuid { get; set; }

    public DateTime accessedUtc { get; set; }

    public string ipAddress { get; set; }

    public int? bytesTransferred { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual AccessType accessType { get; set; }

    public virtual StorageObject storageObject { get; set; }
}