// ============================================================================
//
// DeepSpaceContext.cs — Minimal stub for the DeepSpace EF Core context.
//
// This file will be REPLACED by FoundationCoreTools scaffolding when the
// entity classes are generated from DeepspaceDatabaseGenerator output.
//
// For now, it provides the minimal partial class needed for the project to
// compile with the handwritten DeepSpaceContextCustom.cs.
//
// ============================================================================

using Microsoft.EntityFrameworkCore;

namespace Foundation.DeepSpace.Database
{
    /// <summary>
    /// EF Core DbContext for the DeepSpace metadata database.
    /// 
    /// STUB: This file will be replaced by scaffolded output from FoundationCoreTools.
    /// The scaffolded version will contain DbSet properties for all 12 DeepSpace tables
    /// and the OnModelCreating configuration.
    /// </summary>
    public partial class DeepSpaceContext : DbContext
    {
        //
        // DbSet properties will be generated here by FoundationCoreTools:
        //
        // public virtual DbSet<StorageProviderType> StorageProviderTypes { get; set; }
        // public virtual DbSet<StorageTier> StorageTiers { get; set; }
        // public virtual DbSet<AccessType> AccessTypes { get; set; }
        // public virtual DbSet<MigrationJobStatus> MigrationJobStatuses { get; set; }
        // public virtual DbSet<StorageProvider> StorageProviders { get; set; }
        // public virtual DbSet<StorageObject> StorageObjects { get; set; }
        // public virtual DbSet<StorageObjectVersion> StorageObjectVersions { get; set; }
        // public virtual DbSet<LifecycleRule> LifecycleRules { get; set; }
        // public virtual DbSet<MigrationJob> MigrationJobs { get; set; }
        // public virtual DbSet<ReplicationTarget> ReplicationTargets { get; set; }
        // public virtual DbSet<TenantQuota> TenantQuotas { get; set; }
        // public virtual DbSet<AccessLog> AccessLogs { get; set; }
        //

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //
            // OnModelCreating configuration will be generated by FoundationCoreTools.
            // For now, this is a no-op placeholder.
            //
        }
    }
}
