// ============================================================================
//
// DeepSpaceContextCustom.cs — Handwritten partial class for the DeepSpace EF Core context.
//
// This extends the scaffolded DeepSpaceContext with SQLite configuration,
// UTC date handling, and schema existence checking.
//
// The scaffolded DeepSpaceContext.cs (with DbSet properties and OnModelCreating)
// will be generated by FoundationCoreTools from DeepSpaceDatabaseGenerator output.
//
// ============================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.IO;
using System.Linq;
using static Foundation.DatabaseUtility.DBContextExtensions;

namespace Foundation.DeepSpace.Database
{
    /// <summary>
    /// Handwritten partial class extending the generated DeepSpaceContext.
    /// 
    /// The generated portion provides DbSet properties and OnModelCreating.
    /// This portion provides configuration, constructors, and utility methods.
    /// </summary>
    public partial class DeepSpaceContext : DbContext
    {
        public DbContextConfiguration _configuration;
        public DbContextConfiguration Configuration
        {
            get
            {
                if (_configuration == null)
                {
                    _configuration = new DbContextConfiguration(this);
                }

                return _configuration;
            }
        }


        public DeepSpaceContext()
        {
            this.ChangeTracker.LazyLoadingEnabled = false;
        }


        ///// <summary>
        ///// Constructor accepting pre-built options (used by DeepSpaceDatabaseManager for SQLite).
        ///// </summary>
        //public DeepSpaceContext(DbContextOptions<DeepSpaceContext> options) : base(options)
        //{
        //    this.ChangeTracker.LazyLoadingEnabled = false;
        //}


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.AddInterceptors(UtcDateTimeInterceptor.Instance);

                var builder = new ConfigurationBuilder()
                   .SetBasePath(Directory.GetCurrentDirectory())
                   .AddJsonFile("appsettings.json");

                // Check for a custom or standard environment variable
                if (Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT") == "Development" ||
                    Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Development")
                {
                    builder.AddJsonFile("appsettings.Development.json", optional: true, reloadOnChange: true);
                }

                IConfigurationRoot configuration = builder.Build();
                var connectionString = configuration.GetConnectionString("DeepSpace");

                //
                // Default to SQLite — DeepSpace is designed to be self-contained.
                // If the connection string looks like a Data Source= path, use SQLite.
                // Otherwise, fall back to SQL Server for compatibility.
                //
                if (connectionString != null && connectionString.StartsWith("Data Source=", StringComparison.OrdinalIgnoreCase))
                {
                    optionsBuilder.UseSqlite(connectionString)
                                  .UseLazyLoadingProxies(false)
                                  .AddInterceptors(new Foundation.DeepSpace.DatabaseUtility.SqliteWALModeInterceptor());
                }
                else
                {
                    optionsBuilder.UseSqlServer(connectionString)
                                  .UseLazyLoadingProxies(false)
                                  .AddInterceptors(UtcDateTimeInterceptor.Instance);
                }
            }

            return;
        }


        /// <summary>
        /// Constructor for SQL logging with a custom ILogger.
        /// </summary>
        public DeepSpaceContext(ILogger logger, LogLevel level)
            : base(CreateOptionsWithDebugLogging(logger, level))
        {
        }


        private static DbContextOptions<DeepSpaceContext> CreateOptionsWithDebugLogging(ILogger logger, LogLevel level)
        {
            var optionsBuilder = new DbContextOptionsBuilder<DeepSpaceContext>();

            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory())
                                                    .AddJsonFile("appsettings.json");

            if (Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT") == "Development" ||
                Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Development")
            {
                builder.AddJsonFile("appsettings.Development.json", optional: true, reloadOnChange: true);
            }

            IConfigurationRoot configuration = builder.Build();
            var connectionString = configuration.GetConnectionString("DeepSpace");

            if (connectionString != null && connectionString.StartsWith("Data Source=", StringComparison.OrdinalIgnoreCase))
            {
                optionsBuilder.UseSqlite(connectionString)
                              .EnableSensitiveDataLogging()
                              .LogTo((message) => logger.LogInformation(message), level);
            }
            else
            {
                optionsBuilder.UseSqlServer(connectionString)
                              .EnableSensitiveDataLogging()
                              .LogTo((message) => logger.LogInformation(message), level);
            }

            return optionsBuilder.Options;
        }


        /// <summary>
        /// SQL Server DateTime fields do not store the UTC flag, but SQLite does.
        /// This helper determines the correct UTC conversion strategy.
        /// </summary>
        public bool DoesDatabaseStoreDateWithTimeZone()
        {
            if (this.Database.GetDbConnection().GetType().ToString().Contains("SQLite") == true)
            {
                return true;
            }
            else
            {
                return false;
            }
        }


        /// <summary>
        /// Checks whether the DeepSpace schema tables exist in the database.
        /// Uses the StorageProviderType table as the canary — it's a master data table that must exist.
        /// </summary>
        public bool TablesExistInSchema()
        {
            try
            {
                int tableExistsResult = this.Database.SqlQueryRaw<int>("SELECT count(*) as Value FROM sqlite_master WHERE type='table' AND name='StorageProviderType'").FirstOrDefault();

                return tableExistsResult == 1;
            }
            catch (Exception)
            {
                return false;
            }
        }
    }
}
