// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.DeepSpace.Database;

public partial class StorageTier
{
    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public int? sequence { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<LifecycleRule> LifecycleRulesourceStorageTiers { get; set; } = new List<LifecycleRule>();

    public virtual ICollection<LifecycleRule> LifecycleRuletargetStorageTiers { get; set; } = new List<LifecycleRule>();

    public virtual ICollection<StorageObject> StorageObjects { get; set; } = new List<StorageObject>();
}