// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.DeepSpace.Database;

public partial class StorageObject
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string key { get; set; }

    public int storageProviderId { get; set; }

    public int storageTierId { get; set; }

    public int sizeBytes { get; set; }

    public string contentType { get; set; }

    public string md5Hash { get; set; }

    public string sha256Hash { get; set; }

    public Guid? createdByUserGuid { get; set; }

    public DateTime? lastAccessedUtc { get; set; }

    public int accessCount { get; set; }

    public bool isDeleted { get; set; }

    public DateTime? deletedUtc { get; set; }

    public Guid? deletedByUserGuid { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<AccessLog> AccessLogs { get; set; } = new List<AccessLog>();

    public virtual ICollection<MigrationJob> MigrationJobs { get; set; } = new List<MigrationJob>();

    public virtual ICollection<StorageObjectChangeHistory> StorageObjectChangeHistories { get; set; } = new List<StorageObjectChangeHistory>();

    public virtual ICollection<StorageObjectVersion> StorageObjectVersions { get; set; } = new List<StorageObjectVersion>();

    public virtual StorageProvider storageProvider { get; set; }

    public virtual StorageTier storageTier { get; set; }
}