// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class ActivityEventType
{
    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string iconCssClass { get; set; }

    public string accentColor { get; set; }

    public int? sequence { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<ActivityEvent> ActivityEvents { get; set; } = new List<ActivityEvent>();
}