// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Foundation.BMC.Database;

public partial class BMCContext : DbContext
{
    public BMCContext(DbContextOptions<BMCContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BrickCategory> BrickCategories { get; set; }

    public virtual DbSet<BrickColour> BrickColours { get; set; }

    public virtual DbSet<BrickConnection> BrickConnections { get; set; }

    public virtual DbSet<BrickPart> BrickParts { get; set; }

    public virtual DbSet<BrickPartChangeHistory> BrickPartChangeHistories { get; set; }

    public virtual DbSet<BrickPartColour> BrickPartColours { get; set; }

    public virtual DbSet<BrickPartConnector> BrickPartConnectors { get; set; }

    public virtual DbSet<ConnectorType> ConnectorTypes { get; set; }

    public virtual DbSet<PlacedBrick> PlacedBricks { get; set; }

    public virtual DbSet<PlacedBrickChangeHistory> PlacedBrickChangeHistories { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<ProjectChangeHistory> ProjectChangeHistories { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BrickCategory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__BrickCat__3213E83FE0B904ED");

            entity.ToTable("BrickCategory", "BMC");

            entity.HasIndex(e => e.active, "I_BrickCategory_active");

            entity.HasIndex(e => e.deleted, "I_BrickCategory_deleted");

            entity.HasIndex(e => e.name, "I_BrickCategory_name");

            entity.HasIndex(e => e.objectGuid, "UQ__BrickCat__3E543F946FDF24DF").IsUnique();

            entity.HasIndex(e => e.name, "UQ__BrickCat__72E12F1BA395A106").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<BrickColour>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__BrickCol__3213E83FF6E5FDCB");

            entity.ToTable("BrickColour", "BMC");

            entity.HasIndex(e => e.active, "I_BrickColour_active");

            entity.HasIndex(e => e.deleted, "I_BrickColour_deleted");

            entity.HasIndex(e => e.name, "I_BrickColour_name");

            entity.HasIndex(e => e.ldrawColourCode, "UC_BrickColour_ldrawColourCode").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__BrickCol__3E543F94FC578C20").IsUnique();

            entity.HasIndex(e => e.name, "UQ__BrickCol__72E12F1BE754F94C").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.hexRgb).HasMaxLength(10);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<BrickConnection>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__BrickCon__3213E83F5D52F7C0");

            entity.ToTable("BrickConnection", "BMC");

            entity.HasIndex(e => e.tenantGuid, "I_BrickConnection_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_BrickConnection_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_BrickConnection_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.projectId }, "I_BrickConnection_tenantGuid_projectId");

            entity.HasIndex(e => e.objectGuid, "UQ__BrickCon__3E543F94361BAC49").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);

            entity.HasOne(d => d.project).WithMany(p => p.BrickConnections).HasForeignKey(d => d.projectId);
        });

        modelBuilder.Entity<BrickPart>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__BrickPar__3213E83FD046DFCC");

            entity.ToTable("BrickPart", "BMC");

            entity.HasIndex(e => e.active, "I_BrickPart_active");

            entity.HasIndex(e => e.brickCategoryId, "I_BrickPart_brickCategoryId");

            entity.HasIndex(e => e.deleted, "I_BrickPart_deleted");

            entity.HasIndex(e => e.name, "I_BrickPart_name");

            entity.HasIndex(e => e.ldrawPartId, "UC_BrickPart_ldrawPartId").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__BrickPar__3E543F9497C403DB").IsUnique();

            entity.HasIndex(e => e.name, "UQ__BrickPar__72E12F1B6507E3A3").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.geometryFilePath).HasMaxLength(250);
            entity.Property(e => e.ldrawPartId)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.brickCategory).WithMany(p => p.BrickParts).HasForeignKey(d => d.brickCategoryId);
        });

        modelBuilder.Entity<BrickPartChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__BrickPar__3213E83FCC5C419E");

            entity.ToTable("BrickPartChangeHistory", "BMC");

            entity.HasIndex(e => e.brickPartId, "I_BrickPartChangeHistory_brickPartId");

            entity.HasIndex(e => e.timeStamp, "I_BrickPartChangeHistory_timeStamp");

            entity.HasIndex(e => e.userId, "I_BrickPartChangeHistory_userId");

            entity.HasIndex(e => e.versionNumber, "I_BrickPartChangeHistory_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.brickPart).WithMany(p => p.BrickPartChangeHistories)
                .HasForeignKey(d => d.brickPartId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<BrickPartColour>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__BrickPar__3213E83FB294EC94");

            entity.ToTable("BrickPartColour", "BMC");

            entity.HasIndex(e => e.active, "I_BrickPartColour_active");

            entity.HasIndex(e => e.brickColourId, "I_BrickPartColour_brickColourId");

            entity.HasIndex(e => e.brickPartId, "I_BrickPartColour_brickPartId");

            entity.HasIndex(e => e.deleted, "I_BrickPartColour_deleted");

            entity.HasIndex(e => new { e.brickPartId, e.brickColourId }, "UC_BrickPartColour_brickPartId_brickColourId").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__BrickPar__3E543F94DA3A79A9").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);

            entity.HasOne(d => d.brickColour).WithMany(p => p.BrickPartColours)
                .HasForeignKey(d => d.brickColourId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.brickPart).WithMany(p => p.BrickPartColours)
                .HasForeignKey(d => d.brickPartId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<BrickPartConnector>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__BrickPar__3213E83F19FEB053");

            entity.ToTable("BrickPartConnector", "BMC");

            entity.HasIndex(e => e.active, "I_BrickPartConnector_active");

            entity.HasIndex(e => e.brickPartId, "I_BrickPartConnector_brickPartId");

            entity.HasIndex(e => e.connectorTypeId, "I_BrickPartConnector_connectorTypeId");

            entity.HasIndex(e => e.deleted, "I_BrickPartConnector_deleted");

            entity.HasIndex(e => e.objectGuid, "UQ__BrickPar__3E543F94CABB4665").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);

            entity.HasOne(d => d.brickPart).WithMany(p => p.BrickPartConnectors).HasForeignKey(d => d.brickPartId);

            entity.HasOne(d => d.connectorType).WithMany(p => p.BrickPartConnectors).HasForeignKey(d => d.connectorTypeId);
        });

        modelBuilder.Entity<ConnectorType>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Connecto__3213E83F346423F0");

            entity.ToTable("ConnectorType", "BMC");

            entity.HasIndex(e => e.active, "I_ConnectorType_active");

            entity.HasIndex(e => e.deleted, "I_ConnectorType_deleted");

            entity.HasIndex(e => e.name, "I_ConnectorType_name");

            entity.HasIndex(e => e.objectGuid, "UQ__Connecto__3E543F9426EAFE31").IsUnique();

            entity.HasIndex(e => e.name, "UQ__Connecto__72E12F1B12A094B1").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<PlacedBrick>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__PlacedBr__3213E83F401FB333");

            entity.ToTable("PlacedBrick", "BMC");

            entity.HasIndex(e => e.tenantGuid, "I_PlacedBrick_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_PlacedBrick_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.brickColourId }, "I_PlacedBrick_tenantGuid_brickColourId");

            entity.HasIndex(e => new { e.tenantGuid, e.brickPartId }, "I_PlacedBrick_tenantGuid_brickPartId");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_PlacedBrick_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.projectId }, "I_PlacedBrick_tenantGuid_projectId");

            entity.HasIndex(e => e.objectGuid, "UQ__PlacedBr__3E543F946DBE8D90").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.brickColour).WithMany(p => p.PlacedBricks).HasForeignKey(d => d.brickColourId);

            entity.HasOne(d => d.brickPart).WithMany(p => p.PlacedBricks).HasForeignKey(d => d.brickPartId);

            entity.HasOne(d => d.project).WithMany(p => p.PlacedBricks).HasForeignKey(d => d.projectId);
        });

        modelBuilder.Entity<PlacedBrickChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__PlacedBr__3213E83F80BE553F");

            entity.ToTable("PlacedBrickChangeHistory", "BMC");

            entity.HasIndex(e => e.tenantGuid, "I_PlacedBrickChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.placedBrickId }, "I_PlacedBrickChangeHistory_tenantGuid_placedBrickId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_PlacedBrickChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_PlacedBrickChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_PlacedBrickChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.placedBrick).WithMany(p => p.PlacedBrickChangeHistories)
                .HasForeignKey(d => d.placedBrickId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Project__3213E83F9CC8E12A");

            entity.ToTable("Project", "BMC");

            entity.HasIndex(e => e.tenantGuid, "I_Project_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_Project_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_Project_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "I_Project_tenantGuid_name");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "UC_Project_tenantGuid_name").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__Project__3E543F94AF1D06F9").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);
        });

        modelBuilder.Entity<ProjectChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__ProjectC__3213E83F1FF5291A");

            entity.ToTable("ProjectChangeHistory", "BMC");

            entity.HasIndex(e => e.tenantGuid, "I_ProjectChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.projectId }, "I_ProjectChangeHistory_tenantGuid_projectId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_ProjectChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_ProjectChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_ProjectChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.project).WithMany(p => p.ProjectChangeHistories)
                .HasForeignKey(d => d.projectId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}