// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Foundation.BMC.Database;

public partial class BMCContext : DbContext
{
    public BMCContext(DbContextOptions<BMCContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BrickCategory> BrickCategories { get; set; }

    public virtual DbSet<BrickColour> BrickColours { get; set; }

    public virtual DbSet<BrickConnection> BrickConnections { get; set; }

    public virtual DbSet<BrickPart> BrickParts { get; set; }

    public virtual DbSet<BrickPartChangeHistory> BrickPartChangeHistories { get; set; }

    public virtual DbSet<BrickPartColour> BrickPartColours { get; set; }

    public virtual DbSet<BrickPartConnector> BrickPartConnectors { get; set; }

    public virtual DbSet<ColourFinish> ColourFinishes { get; set; }

    public virtual DbSet<ConnectorType> ConnectorTypes { get; set; }

    public virtual DbSet<PartType> PartTypes { get; set; }

    public virtual DbSet<PlacedBrick> PlacedBricks { get; set; }

    public virtual DbSet<PlacedBrickChangeHistory> PlacedBrickChangeHistories { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<ProjectChangeHistory> ProjectChangeHistories { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BrickCategory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__BrickCat__3213E83FAB6DBCB3");

            entity.ToTable("BrickCategory", "BMC");

            entity.HasIndex(e => e.active, "I_BrickCategory_active");

            entity.HasIndex(e => e.deleted, "I_BrickCategory_deleted");

            entity.HasIndex(e => e.name, "I_BrickCategory_name");

            entity.HasIndex(e => e.objectGuid, "UQ__BrickCat__3E543F9477301172").IsUnique();

            entity.HasIndex(e => e.name, "UQ__BrickCat__72E12F1B739DAC3A").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<BrickColour>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__BrickCol__3213E83FF81A4174");

            entity.ToTable("BrickColour", "BMC");

            entity.HasIndex(e => e.active, "I_BrickColour_active");

            entity.HasIndex(e => e.colourFinishId, "I_BrickColour_colourFinishId");

            entity.HasIndex(e => e.deleted, "I_BrickColour_deleted");

            entity.HasIndex(e => e.name, "I_BrickColour_name");

            entity.HasIndex(e => e.ldrawColourCode, "UC_BrickColour_ldrawColourCode").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__BrickCol__3E543F94E8AABE14").IsUnique();

            entity.HasIndex(e => e.name, "UQ__BrickCol__72E12F1B72673ACE").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.hexEdgeColour).HasMaxLength(10);
            entity.Property(e => e.hexRgb).HasMaxLength(10);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.colourFinish).WithMany(p => p.BrickColours).HasForeignKey(d => d.colourFinishId);
        });

        modelBuilder.Entity<BrickConnection>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__BrickCon__3213E83F778D9E21");

            entity.ToTable("BrickConnection", "BMC");

            entity.HasIndex(e => e.tenantGuid, "I_BrickConnection_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_BrickConnection_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_BrickConnection_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.projectId }, "I_BrickConnection_tenantGuid_projectId");

            entity.HasIndex(e => e.objectGuid, "UQ__BrickCon__3E543F94272B9305").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);

            entity.HasOne(d => d.project).WithMany(p => p.BrickConnections).HasForeignKey(d => d.projectId);
        });

        modelBuilder.Entity<BrickPart>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__BrickPar__3213E83FBB21725F");

            entity.ToTable("BrickPart", "BMC");

            entity.HasIndex(e => e.active, "I_BrickPart_active");

            entity.HasIndex(e => e.brickCategoryId, "I_BrickPart_brickCategoryId");

            entity.HasIndex(e => e.deleted, "I_BrickPart_deleted");

            entity.HasIndex(e => e.name, "I_BrickPart_name");

            entity.HasIndex(e => e.partTypeId, "I_BrickPart_partTypeId");

            entity.HasIndex(e => e.ldrawPartId, "UC_BrickPart_ldrawPartId").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__BrickPar__3E543F948DED8537").IsUnique();

            entity.HasIndex(e => e.name, "UQ__BrickPar__72E12F1BB42C6EFA").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.author).HasMaxLength(100);
            entity.Property(e => e.geometryFilePath).HasMaxLength(250);
            entity.Property(e => e.ldrawCategory).HasMaxLength(100);
            entity.Property(e => e.ldrawPartId)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ldrawTitle).HasMaxLength(250);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.brickCategory).WithMany(p => p.BrickParts).HasForeignKey(d => d.brickCategoryId);

            entity.HasOne(d => d.partType).WithMany(p => p.BrickParts).HasForeignKey(d => d.partTypeId);
        });

        modelBuilder.Entity<BrickPartChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__BrickPar__3213E83F5D26258E");

            entity.ToTable("BrickPartChangeHistory", "BMC");

            entity.HasIndex(e => e.brickPartId, "I_BrickPartChangeHistory_brickPartId");

            entity.HasIndex(e => e.timeStamp, "I_BrickPartChangeHistory_timeStamp");

            entity.HasIndex(e => e.userId, "I_BrickPartChangeHistory_userId");

            entity.HasIndex(e => e.versionNumber, "I_BrickPartChangeHistory_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.brickPart).WithMany(p => p.BrickPartChangeHistories)
                .HasForeignKey(d => d.brickPartId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<BrickPartColour>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__BrickPar__3213E83FA832DD73");

            entity.ToTable("BrickPartColour", "BMC");

            entity.HasIndex(e => e.active, "I_BrickPartColour_active");

            entity.HasIndex(e => e.brickColourId, "I_BrickPartColour_brickColourId");

            entity.HasIndex(e => e.brickPartId, "I_BrickPartColour_brickPartId");

            entity.HasIndex(e => e.deleted, "I_BrickPartColour_deleted");

            entity.HasIndex(e => new { e.brickPartId, e.brickColourId }, "UC_BrickPartColour_brickPartId_brickColourId").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__BrickPar__3E543F94675917FA").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);

            entity.HasOne(d => d.brickColour).WithMany(p => p.BrickPartColours)
                .HasForeignKey(d => d.brickColourId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.brickPart).WithMany(p => p.BrickPartColours)
                .HasForeignKey(d => d.brickPartId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<BrickPartConnector>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__BrickPar__3213E83F82472408");

            entity.ToTable("BrickPartConnector", "BMC");

            entity.HasIndex(e => e.active, "I_BrickPartConnector_active");

            entity.HasIndex(e => e.brickPartId, "I_BrickPartConnector_brickPartId");

            entity.HasIndex(e => e.connectorTypeId, "I_BrickPartConnector_connectorTypeId");

            entity.HasIndex(e => e.deleted, "I_BrickPartConnector_deleted");

            entity.HasIndex(e => e.objectGuid, "UQ__BrickPar__3E543F9430EF9FC8").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);

            entity.HasOne(d => d.brickPart).WithMany(p => p.BrickPartConnectors).HasForeignKey(d => d.brickPartId);

            entity.HasOne(d => d.connectorType).WithMany(p => p.BrickPartConnectors).HasForeignKey(d => d.connectorTypeId);
        });

        modelBuilder.Entity<ColourFinish>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__ColourFi__3213E83FD42AEE69");

            entity.ToTable("ColourFinish", "BMC");

            entity.HasIndex(e => e.active, "I_ColourFinish_active");

            entity.HasIndex(e => e.deleted, "I_ColourFinish_deleted");

            entity.HasIndex(e => e.name, "I_ColourFinish_name");

            entity.HasIndex(e => e.objectGuid, "UQ__ColourFi__3E543F94412FE12E").IsUnique();

            entity.HasIndex(e => e.name, "UQ__ColourFi__72E12F1B92D5F192").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<ConnectorType>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Connecto__3213E83FCA4B98DC");

            entity.ToTable("ConnectorType", "BMC");

            entity.HasIndex(e => e.active, "I_ConnectorType_active");

            entity.HasIndex(e => e.deleted, "I_ConnectorType_deleted");

            entity.HasIndex(e => e.name, "I_ConnectorType_name");

            entity.HasIndex(e => e.objectGuid, "UQ__Connecto__3E543F94118D4AFF").IsUnique();

            entity.HasIndex(e => e.name, "UQ__Connecto__72E12F1B9AE0DA56").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<PartType>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__PartType__3213E83FA21E21B0");

            entity.ToTable("PartType", "BMC");

            entity.HasIndex(e => e.active, "I_PartType_active");

            entity.HasIndex(e => e.deleted, "I_PartType_deleted");

            entity.HasIndex(e => e.name, "I_PartType_name");

            entity.HasIndex(e => e.objectGuid, "UQ__PartType__3E543F9404DFA2E8").IsUnique();

            entity.HasIndex(e => e.name, "UQ__PartType__72E12F1BDCED7380").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.isUserVisible).HasDefaultValue(true);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<PlacedBrick>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__PlacedBr__3213E83F9DAEE6EE");

            entity.ToTable("PlacedBrick", "BMC");

            entity.HasIndex(e => e.tenantGuid, "I_PlacedBrick_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_PlacedBrick_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.brickColourId }, "I_PlacedBrick_tenantGuid_brickColourId");

            entity.HasIndex(e => new { e.tenantGuid, e.brickPartId }, "I_PlacedBrick_tenantGuid_brickPartId");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_PlacedBrick_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.projectId }, "I_PlacedBrick_tenantGuid_projectId");

            entity.HasIndex(e => e.objectGuid, "UQ__PlacedBr__3E543F94625516C5").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.brickColour).WithMany(p => p.PlacedBricks).HasForeignKey(d => d.brickColourId);

            entity.HasOne(d => d.brickPart).WithMany(p => p.PlacedBricks).HasForeignKey(d => d.brickPartId);

            entity.HasOne(d => d.project).WithMany(p => p.PlacedBricks).HasForeignKey(d => d.projectId);
        });

        modelBuilder.Entity<PlacedBrickChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__PlacedBr__3213E83FF7F4D5B0");

            entity.ToTable("PlacedBrickChangeHistory", "BMC");

            entity.HasIndex(e => e.tenantGuid, "I_PlacedBrickChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.placedBrickId }, "I_PlacedBrickChangeHistory_tenantGuid_placedBrickId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_PlacedBrickChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_PlacedBrickChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_PlacedBrickChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.placedBrick).WithMany(p => p.PlacedBrickChangeHistories)
                .HasForeignKey(d => d.placedBrickId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Project__3213E83F69B85148");

            entity.ToTable("Project", "BMC");

            entity.HasIndex(e => e.tenantGuid, "I_Project_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_Project_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_Project_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "I_Project_tenantGuid_name");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "UC_Project_tenantGuid_name").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__Project__3E543F949FBA6DAC").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);
        });

        modelBuilder.Entity<ProjectChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__ProjectC__3213E83F2F2B1F64");

            entity.ToTable("ProjectChangeHistory", "BMC");

            entity.HasIndex(e => e.tenantGuid, "I_ProjectChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.projectId }, "I_ProjectChangeHistory_tenantGuid_projectId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_ProjectChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_ProjectChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_ProjectChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.project).WithMany(p => p.ProjectChangeHistories)
                .HasForeignKey(d => d.projectId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}