// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class BrickPart
{
    public int id { get; set; }

    public string name { get; set; }

    public string rebrickablePartNum { get; set; }

    public string rebrickablePartUrl { get; set; }

    public string rebrickableImgUrl { get; set; }

    public string ldrawPartId { get; set; }

    public string bricklinkId { get; set; }

    public string brickowlId { get; set; }

    public string legoDesignId { get; set; }

    public string ldrawTitle { get; set; }

    public string ldrawCategory { get; set; }

    public int partTypeId { get; set; }

    public string keywords { get; set; }

    public string author { get; set; }

    public int brickCategoryId { get; set; }

    public float? widthLdu { get; set; }

    public float? heightLdu { get; set; }

    public float? depthLdu { get; set; }

    public float? massGrams { get; set; }

    public float? momentOfInertiaX { get; set; }

    public float? momentOfInertiaY { get; set; }

    public float? momentOfInertiaZ { get; set; }

    public float? frictionCoefficient { get; set; }

    public string materialType { get; set; }

    public float? centerOfMassX { get; set; }

    public float? centerOfMassY { get; set; }

    public float? centerOfMassZ { get; set; }

    public string geometryFileName { get; set; }

    public long? geometrySize { get; set; }

    public byte[] geometryData { get; set; }

    public string geometryMimeType { get; set; }

    public string geometryFileFormat { get; set; }

    public string geometryOriginalFileName { get; set; }

    public float? boundingBoxMinX { get; set; }

    public float? boundingBoxMinY { get; set; }

    public float? boundingBoxMinZ { get; set; }

    public float? boundingBoxMaxX { get; set; }

    public float? boundingBoxMaxY { get; set; }

    public float? boundingBoxMaxZ { get; set; }

    public int? subFileCount { get; set; }

    public int? polygonCount { get; set; }

    public int? toothCount { get; set; }

    public float? gearRatio { get; set; }

    public DateTime? lastModifiedDate { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<BrickElement> BrickElements { get; set; } = new List<BrickElement>();

    public virtual ICollection<BrickPartChangeHistory> BrickPartChangeHistories { get; set; } = new List<BrickPartChangeHistory>();

    public virtual ICollection<BrickPartColour> BrickPartColours { get; set; } = new List<BrickPartColour>();

    public virtual ICollection<BrickPartConnector> BrickPartConnectors { get; set; } = new List<BrickPartConnector>();

    public virtual ICollection<BrickPartRelationship> BrickPartRelationshipchildBrickParts { get; set; } = new List<BrickPartRelationship>();

    public virtual ICollection<BrickPartRelationship> BrickPartRelationshipparentBrickParts { get; set; } = new List<BrickPartRelationship>();

    public virtual ICollection<LegoSetPart> LegoSetParts { get; set; } = new List<LegoSetPart>();

    public virtual ICollection<ModelStepPart> ModelStepParts { get; set; } = new List<ModelStepPart>();

    public virtual ICollection<PartSubFileReference> PartSubFileReferenceparentBrickParts { get; set; } = new List<PartSubFileReference>();

    public virtual ICollection<PartSubFileReference> PartSubFileReferencereferencedBrickParts { get; set; } = new List<PartSubFileReference>();

    public virtual ICollection<PlacedBrick> PlacedBricks { get; set; } = new List<PlacedBrick>();

    public virtual ICollection<UserCollectionPart> UserCollectionParts { get; set; } = new List<UserCollectionPart>();

    public virtual ICollection<UserLostPart> UserLostParts { get; set; } = new List<UserLostPart>();

    public virtual ICollection<UserPartListItem> UserPartListItems { get; set; } = new List<UserPartListItem>();

    public virtual ICollection<UserWishlistItem> UserWishlistItems { get; set; } = new List<UserWishlistItem>();

    public virtual BrickCategory brickCategory { get; set; }

    public virtual PartType partType { get; set; }
}