// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class BrickEconomyUserLink
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string encryptedApiKey { get; set; }

    public bool syncEnabled { get; set; }

    public DateTime? lastSyncDate { get; set; }

    public string lastSyncError { get; set; }

    public int? dailyQuotaUsed { get; set; }

    public DateTime? quotaResetDate { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }
}