// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class BrickPart
{
    public int id { get; set; }

    public string name { get; set; }

    public string ldrawPartId { get; set; }

    public string ldrawTitle { get; set; }

    public string ldrawCategory { get; set; }

    public string partType { get; set; }

    public string keywords { get; set; }

    public string author { get; set; }

    public int? brickCategoryId { get; set; }

    public float widthLdu { get; set; }

    public float heightLdu { get; set; }

    public float depthLdu { get; set; }

    public float massGrams { get; set; }

    public string geometryFilePath { get; set; }

    public int? toothCount { get; set; }

    public float? gearRatio { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<BrickPartChangeHistory> BrickPartChangeHistories { get; set; } = new List<BrickPartChangeHistory>();

    public virtual ICollection<BrickPartColour> BrickPartColours { get; set; } = new List<BrickPartColour>();

    public virtual ICollection<BrickPartConnector> BrickPartConnectors { get; set; } = new List<BrickPartConnector>();

    public virtual ICollection<PlacedBrick> PlacedBricks { get; set; } = new List<PlacedBrick>();

    public virtual BrickCategory brickCategory { get; set; }
}