// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class BrickColour
{
    public int id { get; set; }

    public string name { get; set; }

    public int ldrawColourCode { get; set; }

    public string hexRgb { get; set; }

    public string hexEdgeColour { get; set; }

    public int? alpha { get; set; }

    public bool isTransparent { get; set; }

    public bool isMetallic { get; set; }

    public string finishType { get; set; }

    public int? luminance { get; set; }

    public int? legoColourId { get; set; }

    public int? sequence { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<BrickPartColour> BrickPartColours { get; set; } = new List<BrickPartColour>();

    public virtual ICollection<PlacedBrick> PlacedBricks { get; set; } = new List<PlacedBrick>();
}