// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class BrickColour
{
    public int id { get; set; }

    public string name { get; set; }

    public int rebrickableColorId { get; set; }

    public int? ldrawColourCode { get; set; }

    public int? bricklinkColorId { get; set; }

    public int? brickowlColorId { get; set; }

    public string hexRgb { get; set; }

    public string hexEdgeColour { get; set; }

    public int? alpha { get; set; }

    public bool isTransparent { get; set; }

    public bool isMetallic { get; set; }

    public int colourFinishId { get; set; }

    public int? luminance { get; set; }

    public int? legoColourId { get; set; }

    public int? sequence { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<BrickElement> BrickElements { get; set; } = new List<BrickElement>();

    public virtual ICollection<BrickPartColour> BrickPartColours { get; set; } = new List<BrickPartColour>();

    public virtual ICollection<LegoSetPart> LegoSetParts { get; set; } = new List<LegoSetPart>();

    public virtual ICollection<ModelStepPart> ModelStepParts { get; set; } = new List<ModelStepPart>();

    public virtual ICollection<PlacedBrick> PlacedBricks { get; set; } = new List<PlacedBrick>();

    public virtual ICollection<UserCollectionPart> UserCollectionParts { get; set; } = new List<UserCollectionPart>();

    public virtual ICollection<UserLostPart> UserLostParts { get; set; } = new List<UserLostPart>();

    public virtual ICollection<UserPartListItem> UserPartListItems { get; set; } = new List<UserPartListItem>();

    public virtual ICollection<UserWishlistItem> UserWishlistItems { get; set; } = new List<UserWishlistItem>();

    public virtual ColourFinish colourFinish { get; set; }
}