// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class BrickSetSetReview
{
    public int id { get; set; }

    public int legoSetId { get; set; }

    public string reviewAuthor { get; set; }

    public DateTime? reviewDate { get; set; }

    public string reviewTitle { get; set; }

    public string reviewBody { get; set; }

    public int? overallRating { get; set; }

    public int? buildingExperienceRating { get; set; }

    public int? valueForMoneyRating { get; set; }

    public int? partsRating { get; set; }

    public int? playabilityRating { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual LegoSet legoSet { get; set; }
}