// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class BuildManual
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int projectId { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public float? pageWidthMm { get; set; }

    public float? pageHeightMm { get; set; }

    public bool isPublished { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<BuildManualChangeHistory> BuildManualChangeHistories { get; set; } = new List<BuildManualChangeHistory>();

    public virtual ICollection<BuildManualPage> BuildManualPages { get; set; } = new List<BuildManualPage>();

    public virtual Project project { get; set; }
}