// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class BuildChallengeEntry
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int buildChallengeId { get; set; }

    public int publishedMocId { get; set; }

    public DateTime submittedDate { get; set; }

    public string entryNotes { get; set; }

    public int voteCount { get; set; }

    public bool isWinner { get; set; }

    public bool isDisqualified { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual BuildChallenge buildChallenge { get; set; }

    public virtual PublishedMoc publishedMoc { get; set; }
}