// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class BuildChallengeChangeHistory
{
    public int id { get; set; }

    public int buildChallengeId { get; set; }

    public int versionNumber { get; set; }

    public DateTime timeStamp { get; set; }

    public int userId { get; set; }

    public string data { get; set; }

    public virtual BuildChallenge buildChallenge { get; set; }
}