// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class BuildManualPage
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int buildManualId { get; set; }

    public int? pageNum { get; set; }

    public string title { get; set; }

    public string notes { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<BuildManualStep> BuildManualSteps { get; set; } = new List<BuildManualStep>();

    public virtual BuildManual buildManual { get; set; }
}