// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class CompiledGlb
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int projectId { get; set; }

    public int projectVersionNumber { get; set; }

    public bool includesEdgeLines { get; set; }

    public byte[] glbData { get; set; }

    public long glbSizeBytes { get; set; }

    public int? triangleCount { get; set; }

    public int? stepCount { get; set; }

    public DateTime compiledAt { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual Project project { get; set; }
}