// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class LegoSet
{
    public int id { get; set; }

    public string name { get; set; }

    public string setNumber { get; set; }

    public int year { get; set; }

    public int partCount { get; set; }

    public int? legoThemeId { get; set; }

    public string imageUrl { get; set; }

    public string brickLinkUrl { get; set; }

    public string rebrickableUrl { get; set; }

    public string rebrickableSetNum { get; set; }

    public DateTime? lastModifiedDate { get; set; }

    public int? brickSetId { get; set; }

    public string brickSetUrl { get; set; }

    public decimal? retailPriceUS { get; set; }

    public decimal? retailPriceUK { get; set; }

    public decimal? retailPriceCA { get; set; }

    public decimal? retailPriceEU { get; set; }

    public string instructionsUrl { get; set; }

    public string subtheme { get; set; }

    public string availability { get; set; }

    public int? minifigCount { get; set; }

    public float? brickSetRating { get; set; }

    public int? brickSetReviewCount { get; set; }

    public DateTime? brickSetLastEnrichedDate { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<BrickSetSetReview> BrickSetSetReviews { get; set; } = new List<BrickSetSetReview>();

    public virtual ICollection<LegoSetMinifig> LegoSetMinifigs { get; set; } = new List<LegoSetMinifig>();

    public virtual ICollection<LegoSetPart> LegoSetParts { get; set; } = new List<LegoSetPart>();

    public virtual ICollection<LegoSetSubset> LegoSetSubsetchildLegoSets { get; set; } = new List<LegoSetSubset>();

    public virtual ICollection<LegoSetSubset> LegoSetSubsetparentLegoSets { get; set; } = new List<LegoSetSubset>();

    public virtual ICollection<UserCollectionSetImport> UserCollectionSetImports { get; set; } = new List<UserCollectionSetImport>();

    public virtual ICollection<UserLostPart> UserLostParts { get; set; } = new List<UserLostPart>();

    public virtual ICollection<UserSetListItem> UserSetListItems { get; set; } = new List<UserSetListItem>();

    public virtual ICollection<UserSetOwnership> UserSetOwnerships { get; set; } = new List<UserSetOwnership>();

    public virtual LegoTheme legoTheme { get; set; }
}