// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class LegoTheme
{
    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public int? legoThemeId { get; set; }

    public int? rebrickableThemeId { get; set; }

    public int? sequence { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<LegoTheme> InverselegoTheme { get; set; } = new List<LegoTheme>();

    public virtual ICollection<LegoSet> LegoSets { get; set; } = new List<LegoSet>();

    public virtual ICollection<UserProfilePreferredTheme> UserProfilePreferredThemes { get; set; } = new List<UserProfilePreferredTheme>();

    public virtual LegoTheme legoTheme { get; set; }
}