// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class LegoSetSubset
{
    public int id { get; set; }

    public int parentLegoSetId { get; set; }

    public int childLegoSetId { get; set; }

    public int? quantity { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual LegoSet childLegoSet { get; set; }

    public virtual LegoSet parentLegoSet { get; set; }
}