// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class MocCollaborator
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int publishedMocId { get; set; }

    public Guid collaboratorTenantGuid { get; set; }

    public string accessLevel { get; set; }

    public DateTime invitedDate { get; set; }

    public DateTime? acceptedDate { get; set; }

    public bool isAccepted { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<MocCollaboratorChangeHistory> MocCollaboratorChangeHistories { get; set; } = new List<MocCollaboratorChangeHistory>();

    public virtual PublishedMoc publishedMoc { get; set; }
}