// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class MocFork
{
    public int id { get; set; }

    public int forkedMocId { get; set; }

    public int sourceMocId { get; set; }

    public int? mocVersionId { get; set; }

    public Guid forkerTenantGuid { get; set; }

    public DateTime forkedDate { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual PublishedMoc forkedMoc { get; set; }

    public virtual MocVersion mocVersion { get; set; }

    public virtual PublishedMoc sourceMoc { get; set; }
}