// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class ModelStepPart
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int modelBuildStepId { get; set; }

    public int? brickPartId { get; set; }

    public int? brickColourId { get; set; }

    public string partFileName { get; set; }

    public int colorCode { get; set; }

    public float? positionX { get; set; }

    public float? positionY { get; set; }

    public float? positionZ { get; set; }

    public string transformMatrix { get; set; }

    public int? sequence { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual BrickColour brickColour { get; set; }

    public virtual BrickPart brickPart { get; set; }

    public virtual ModelBuildStep modelBuildStep { get; set; }
}