// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class ModelBuildStep
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int modelSubFileId { get; set; }

    public int stepNumber { get; set; }

    public string rotationType { get; set; }

    public float? rotationX { get; set; }

    public float? rotationY { get; set; }

    public float? rotationZ { get; set; }

    public string description { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<ModelStepPart> ModelStepParts { get; set; } = new List<ModelStepPart>();

    public virtual ModelSubFile modelSubFile { get; set; }
}