// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class ModerationAction
{
    public long id { get; set; }

    public Guid moderatorTenantGuid { get; set; }

    public string actionType { get; set; }

    public Guid? targetTenantGuid { get; set; }

    public string targetEntityType { get; set; }

    public long? targetEntityId { get; set; }

    public string reason { get; set; }

    public DateTime actionDate { get; set; }

    public int? contentReportId { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ContentReport contentReport { get; set; }
}