// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class ModelSubFile
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int modelDocumentId { get; set; }

    public string fileName { get; set; }

    public bool isMainModel { get; set; }

    public int? parentModelSubFileId { get; set; }

    public int? sequence { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<ModelSubFile> InverseparentModelSubFile { get; set; } = new List<ModelSubFile>();

    public virtual ICollection<ModelBuildStep> ModelBuildSteps { get; set; } = new List<ModelBuildStep>();

    public virtual ModelDocument modelDocument { get; set; }

    public virtual ModelSubFile parentModelSubFile { get; set; }
}