// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class PendingRegistration
{
    public int id { get; set; }

    public string accountName { get; set; }

    public string emailAddress { get; set; }

    public string displayName { get; set; }

    public string passwordHash { get; set; }

    public string verificationCode { get; set; }

    public DateTime codeExpiresAt { get; set; }

    public int verificationAttempts { get; set; }

    public string status { get; set; }

    public DateTime createdAt { get; set; }

    public DateTime? verifiedAt { get; set; }

    public DateTime? provisionedAt { get; set; }

    public string ipAddress { get; set; }

    public string userAgent { get; set; }

    public string verificationChannel { get; set; }

    public string failureReason { get; set; }

    public int? provisionedSecurityUserId { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }
}