// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class PlacedBrick
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int projectId { get; set; }

    public int brickPartId { get; set; }

    public int brickColourId { get; set; }

    public float? positionX { get; set; }

    public float? positionY { get; set; }

    public float? positionZ { get; set; }

    public float? rotationX { get; set; }

    public float? rotationY { get; set; }

    public float? rotationZ { get; set; }

    public float? rotationW { get; set; }

    public int? buildStepNumber { get; set; }

    public bool isHidden { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<BrickConnection> BrickConnectionsourcePlacedBricks { get; set; } = new List<BrickConnection>();

    public virtual ICollection<BrickConnection> BrickConnectiontargetPlacedBricks { get; set; } = new List<BrickConnection>();

    public virtual ICollection<BuildStepAnnotation> BuildStepAnnotations { get; set; } = new List<BuildStepAnnotation>();

    public virtual ICollection<BuildStepPart> BuildStepParts { get; set; } = new List<BuildStepPart>();

    public virtual ICollection<PlacedBrickChangeHistory> PlacedBrickChangeHistories { get; set; } = new List<PlacedBrickChangeHistory>();

    public virtual ICollection<SubmodelPlacedBrick> SubmodelPlacedBricks { get; set; } = new List<SubmodelPlacedBrick>();

    public virtual BrickColour brickColour { get; set; }

    public virtual BrickPart brickPart { get; set; }

    public virtual Project project { get; set; }
}