// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class ProjectTagAssignment
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int projectId { get; set; }

    public int projectTagId { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual Project project { get; set; }

    public virtual ProjectTag projectTag { get; set; }
}