// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class ProjectChangeHistory
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int projectId { get; set; }

    public int versionNumber { get; set; }

    public DateTime timeStamp { get; set; }

    public int userId { get; set; }

    public string data { get; set; }

    public virtual Project project { get; set; }
}