// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class Project
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int? userId { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string notes { get; set; }

    public string thumbnailImagePath { get; set; }

    public int? partCount { get; set; }

    public DateTime? lastBuildDate { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<BrickConnection> BrickConnections { get; set; } = new List<BrickConnection>();

    public virtual ICollection<BuildManual> BuildManuals { get; set; } = new List<BuildManual>();

    public virtual ICollection<ModelDocument> ModelDocuments { get; set; } = new List<ModelDocument>();

    public virtual ICollection<PlacedBrick> PlacedBricks { get; set; } = new List<PlacedBrick>();

    public virtual ICollection<ProjectCameraPreset> ProjectCameraPresets { get; set; } = new List<ProjectCameraPreset>();

    public virtual ICollection<ProjectChangeHistory> ProjectChangeHistories { get; set; } = new List<ProjectChangeHistory>();

    public virtual ICollection<ProjectExport> ProjectExports { get; set; } = new List<ProjectExport>();

    public virtual ICollection<ProjectReferenceImage> ProjectReferenceImages { get; set; } = new List<ProjectReferenceImage>();

    public virtual ICollection<ProjectRender> ProjectRenders { get; set; } = new List<ProjectRender>();

    public virtual ICollection<ProjectTagAssignment> ProjectTagAssignments { get; set; } = new List<ProjectTagAssignment>();

    public virtual ICollection<PublishedMoc> PublishedMocs { get; set; } = new List<PublishedMoc>();

    public virtual ICollection<Submodel> Submodels { get; set; } = new List<Submodel>();
}