// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class PublishedMocImage
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int publishedMocId { get; set; }

    public string imagePath { get; set; }

    public string caption { get; set; }

    public int? sequence { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual PublishedMoc publishedMoc { get; set; }
}