// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class SharedInstruction
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int? buildManualId { get; set; }

    public int? publishedMocId { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string formatType { get; set; }

    public string filePath { get; set; }

    public bool isPublished { get; set; }

    public DateTime? publishedDate { get; set; }

    public int downloadCount { get; set; }

    public int? pageCount { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<SharedInstructionChangeHistory> SharedInstructionChangeHistories { get; set; } = new List<SharedInstructionChangeHistory>();

    public virtual BuildManual buildManual { get; set; }

    public virtual PublishedMoc publishedMoc { get; set; }
}