// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class SubmodelInstance
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int submodelId { get; set; }

    public float? positionX { get; set; }

    public float? positionY { get; set; }

    public float? positionZ { get; set; }

    public float? rotationX { get; set; }

    public float? rotationY { get; set; }

    public float? rotationZ { get; set; }

    public float? rotationW { get; set; }

    public int colourCode { get; set; }

    public int buildStepNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual Submodel submodel { get; set; }
}