// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class Submodel
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int projectId { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public int? submodelId { get; set; }

    public int? sequence { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<Submodel> Inversesubmodel { get; set; } = new List<Submodel>();

    public virtual ICollection<SubmodelChangeHistory> SubmodelChangeHistories { get; set; } = new List<SubmodelChangeHistory>();

    public virtual ICollection<SubmodelPlacedBrick> SubmodelPlacedBricks { get; set; } = new List<SubmodelPlacedBrick>();

    public virtual Project project { get; set; }

    public virtual Submodel submodel { get; set; }
}