// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class UserProfilePreferredTheme
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int userProfileId { get; set; }

    public int legoThemeId { get; set; }

    public int? sequence { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual LegoTheme legoTheme { get; set; }

    public virtual UserProfile userProfile { get; set; }
}