// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class UserPartList
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string name { get; set; }

    public bool isBuildable { get; set; }

    public int? rebrickableListId { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<UserPartListChangeHistory> UserPartListChangeHistories { get; set; } = new List<UserPartListChangeHistory>();

    public virtual ICollection<UserPartListItem> UserPartListItems { get; set; } = new List<UserPartListItem>();
}