// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class UserProfile
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string displayName { get; set; }

    public string bio { get; set; }

    public string location { get; set; }

    public string avatarImagePath { get; set; }

    public string profileBannerImagePath { get; set; }

    public string websiteUrl { get; set; }

    public bool isPublic { get; set; }

    public DateTime? memberSinceDate { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<UserProfileChangeHistory> UserProfileChangeHistories { get; set; } = new List<UserProfileChangeHistory>();

    public virtual ICollection<UserProfileLink> UserProfileLinks { get; set; } = new List<UserProfileLink>();

    public virtual ICollection<UserProfileStat> UserProfileStats { get; set; } = new List<UserProfileStat>();
}