// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.BMC.Database;

public partial class UserSetListItem
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int userSetListId { get; set; }

    public int legoSetId { get; set; }

    public int quantity { get; set; }

    public bool includeSpares { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual LegoSet legoSet { get; set; }

    public virtual UserSetList userSetList { get; set; }
}