//
// User Session Service
//
// Angular service for managing user sessions including viewing and revocation.
// Calls the SessionsController API endpoints.
//
// AI-generated: This service was generated by AI assistant to integrate
// session management into the user detail component.
//

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { AuthService } from './auth.service';


//
// User Session Types
//

export interface UserSessionInfo {
    sessionId: number;
    username: string;
    displayName?: string;
    clientApplication?: string;
    sessionStart: Date;
    expiresAt: Date;
    isExpired: boolean;
    ipAddress?: string;
    userAgent?: string;
    loginMethod?: string;
    isActive: boolean;
}

export interface RevokeResult {
    success: boolean;
    message: string;
}

export interface RevokeAllResult {
    success: boolean;
    revokedCount: number;
    message: string;
}

export interface RevokeAndLockResult {
    success: boolean;
    message: string;
    revokedCount: number;
    accountLocked: boolean;
    targetUsername: string;
}


@Injectable({
    providedIn: 'root'
})
export class UserSessionManagementService {

    constructor(
        private http: HttpClient,
        private authService: AuthService
    ) { }


    /**
     * Get all sessions for a specific user.
     * Requires admin permissions.
     */
    getUserSessions(userId: number): Observable<UserSessionInfo[]> {
        return this.http.get<UserSessionInfo[]>(
            `/api/sessions/user/${userId}`,
            { headers: this.authService.GetAuthenticationHeaders() }
        );
    }


    /**
     * Revoke a specific session by ID.
     * Requires admin permissions.
     */
    revokeSession(sessionId: number, reason?: string): Observable<RevokeResult> {
        return this.http.post<RevokeResult>(
            `/api/sessions/${sessionId}/revoke`,
            { reason: reason || 'Administrative action' },
            { headers: this.authService.GetAuthenticationHeaders() }
        );
    }


    /**
     * Revoke all sessions for a specific user.
     * Requires admin permissions.
     */
    revokeAllUserSessions(userId: number, reason?: string): Observable<RevokeAllResult> {
        return this.http.post<RevokeAllResult>(
            `/api/sessions/user/${userId}/revoke-all`,
            { reason: reason || 'Administrative action - all sessions revoked' },
            { headers: this.authService.GetAuthenticationHeaders() }
        );
    }


    /**
     * Revoke all sessions AND lock the user's account.
     * This is the highest security operation.
     * Requires admin permissions.
     */
    revokeAllAndLockAccount(userId: number, reason?: string): Observable<RevokeAndLockResult> {
        return this.http.post<RevokeAndLockResult>(
            `/api/sessions/user/${userId}/revoke-and-lock`,
            { reason: reason || 'Security action - account locked' },
            { headers: this.authService.GetAuthenticationHeaders() }
        );
    }
}
