// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Telemetry.Database;

public partial class TelemetryNetworkHealth
{
    public int id { get; set; }

    public int telemetrySnapshotId { get; set; }

    public string interfaceName { get; set; }

    public string interfaceDescription { get; set; }

    public double? linkSpeedMbps { get; set; }

    public long? bytesSentTotal { get; set; }

    public long? bytesReceivedTotal { get; set; }

    public double? bytesSentPerSecond { get; set; }

    public double? bytesReceivedPerSecond { get; set; }

    public double? utilizationPercent { get; set; }

    public string status { get; set; }

    public bool isActive { get; set; }

    public virtual TelemetrySnapshot telemetrySnapshot { get; set; }
}