// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Security.Database;

public partial class LoginAttempt
{
    public int id { get; set; }

    public DateTime timeStamp { get; set; }

    public string userName { get; set; }

    public int? passwordHash { get; set; }

    public string resource { get; set; }

    public string sessionId { get; set; }

    public string ipAddress { get; set; }

    public string userAgent { get; set; }

    public string value { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }
}