// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Security.Database;

public partial class SecurityTeam
{
    public int id { get; set; }

    public int securityDepartmentId { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<SecurityTeamUser> SecurityTeamUsers { get; set; } = new List<SecurityTeamUser>();

    public virtual ICollection<SecurityUser> SecurityUsers { get; set; } = new List<SecurityUser>();

    public virtual SecurityDepartment securityDepartment { get; set; }
}