// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Security.Database;

public partial class SecurityUserSecurityGroup
{
    public int id { get; set; }

    public int securityUserId { get; set; }

    public int securityGroupId { get; set; }

    public string comments { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual SecurityGroup securityGroup { get; set; }

    public virtual SecurityUser securityUser { get; set; }
}