// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Security.Database;

public partial class SecurityTeamUser
{
    public int id { get; set; }

    public int securityTeamId { get; set; }

    public int securityUserId { get; set; }

    public bool canRead { get; set; }

    public bool canWrite { get; set; }

    public bool canChangeHierarchy { get; set; }

    public bool canChangeOwner { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual SecurityTeam securityTeam { get; set; }

    public virtual SecurityUser securityUser { get; set; }
}