// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Security.Database;

public partial class SecurityUser
{
    public int id { get; set; }

    public string accountName { get; set; }

    public bool activeDirectoryAccount { get; set; }

    public string password { get; set; }

    public bool canLogin { get; set; }

    public bool mustChangePassword { get; set; }

    public string firstName { get; set; }

    public string middleName { get; set; }

    public string lastName { get; set; }

    public DateTime? dateOfBirth { get; set; }

    public string emailAddress { get; set; }

    public string cellPhoneNumber { get; set; }

    public string phoneNumber { get; set; }

    public string phoneExtension { get; set; }

    public string description { get; set; }

    public int? securityUserTitleId { get; set; }

    public int? reportsToSecurityUserId { get; set; }

    public string authenticationDomain { get; set; }

    public int? failedLoginCount { get; set; }

    public DateTime? lastLoginAttempt { get; set; }

    public DateTime? mostRecentActivity { get; set; }

    public string alternateIdentifier { get; set; }

    public byte[] image { get; set; }

    public string settings { get; set; }

    public int? securityTenantId { get; set; }

    public int readPermissionLevel { get; set; }

    public int writePermissionLevel { get; set; }

    public int? securityOrganizationId { get; set; }

    public int? securityDepartmentId { get; set; }

    public int? securityTeamId { get; set; }

    public string authenticationToken { get; set; }

    public DateTime? authenticationTokenExpiry { get; set; }

    public string twoFactorToken { get; set; }

    public DateTime? twoFactorTokenExpiry { get; set; }

    public bool? twoFactorSendByEmail { get; set; }

    public bool? twoFactorSendBySMS { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<EntityDataToken> EntityDataTokens { get; set; } = new List<EntityDataToken>();

    public virtual ICollection<SecurityUser> InversereportsToSecurityUser { get; set; } = new List<SecurityUser>();

    public virtual ICollection<SecurityDepartmentUser> SecurityDepartmentUsers { get; set; } = new List<SecurityDepartmentUser>();

    public virtual ICollection<SecurityOrganizationUser> SecurityOrganizationUsers { get; set; } = new List<SecurityOrganizationUser>();

    public virtual ICollection<SecurityTeamUser> SecurityTeamUsers { get; set; } = new List<SecurityTeamUser>();

    public virtual ICollection<SecurityTenantUser> SecurityTenantUsers { get; set; } = new List<SecurityTenantUser>();

    public virtual ICollection<SecurityUserEvent> SecurityUserEvents { get; set; } = new List<SecurityUserEvent>();

    public virtual ICollection<SecurityUserPasswordResetToken> SecurityUserPasswordResetTokens { get; set; } = new List<SecurityUserPasswordResetToken>();

    public virtual ICollection<SecurityUserSecurityGroup> SecurityUserSecurityGroups { get; set; } = new List<SecurityUserSecurityGroup>();

    public virtual ICollection<SecurityUserSecurityRole> SecurityUserSecurityRoles { get; set; } = new List<SecurityUserSecurityRole>();

    public virtual SecurityUser reportsToSecurityUser { get; set; }

    public virtual SecurityDepartment securityDepartment { get; set; }

    public virtual SecurityOrganization securityOrganization { get; set; }

    public virtual SecurityTeam securityTeam { get; set; }

    public virtual SecurityTenant securityTenant { get; set; }

    public virtual SecurityUserTitle securityUserTitle { get; set; }
}