// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Security.Database;

public partial class SecurityGroup
{
    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<SecurityGroupSecurityRole> SecurityGroupSecurityRoles { get; set; } = new List<SecurityGroupSecurityRole>();

    public virtual ICollection<SecurityUserSecurityGroup> SecurityUserSecurityGroups { get; set; } = new List<SecurityUserSecurityGroup>();
}