// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Security.Database;

public partial class SecurityUserEvent
{
    public int id { get; set; }

    public int securityUserId { get; set; }

    public int securityUserEventTypeId { get; set; }

    public DateTime timeStamp { get; set; }

    public string comments { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual SecurityUser securityUser { get; set; }

    public virtual SecurityUserEventType securityUserEventType { get; set; }
}