// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Security.Database;

public partial class SecurityTenantUser
{
    public int id { get; set; }

    public int securityTenantId { get; set; }

    public int securityUserId { get; set; }

    public bool isOwner { get; set; }

    public bool canRead { get; set; }

    public bool canWrite { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual SecurityTenant securityTenant { get; set; }

    public virtual SecurityUser securityUser { get; set; }
}