// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Security.Database;

public partial class UserSession
{
    public int id { get; set; }

    public int securityUserId { get; set; }

    public Guid objectGuid { get; set; }

    public string tokenId { get; set; }

    public DateTime sessionStart { get; set; }

    public DateTime expiresAt { get; set; }

    public string ipAddress { get; set; }

    public string userAgent { get; set; }

    public string loginMethod { get; set; }

    public string clientApplication { get; set; }

    public bool isRevoked { get; set; }

    public DateTime? revokedAt { get; set; }

    public string revokedBy { get; set; }

    public string revokedReason { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual SecurityUser securityUser { get; set; }
}