// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Auditor.Database;

public partial class AuditModule
{
    public int id { get; set; }

    public string name { get; set; }

    public string comments { get; set; }

    public DateTime? firstAccess { get; set; }

    public virtual ICollection<AuditEvent> AuditEvents { get; set; } = new List<AuditEvent>();

    public virtual ICollection<AuditModuleEntity> AuditModuleEntities { get; set; } = new List<AuditModuleEntity>();
}