// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Foundation.Auditor.Database;

public partial class AuditorContext : DbContext
{
    public AuditorContext(DbContextOptions<AuditorContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AuditAccessType> AuditAccessTypes { get; set; }

    public virtual DbSet<AuditEvent> AuditEvents { get; set; }

    public virtual DbSet<AuditEventEntityState> AuditEventEntityStates { get; set; }

    public virtual DbSet<AuditEventErrorMessage> AuditEventErrorMessages { get; set; }

    public virtual DbSet<AuditHostSystem> AuditHostSystems { get; set; }

    public virtual DbSet<AuditModule> AuditModules { get; set; }

    public virtual DbSet<AuditModuleEntity> AuditModuleEntities { get; set; }

    public virtual DbSet<AuditPlanB> AuditPlanBs { get; set; }

    public virtual DbSet<AuditResource> AuditResources { get; set; }

    public virtual DbSet<AuditSession> AuditSessions { get; set; }

    public virtual DbSet<AuditSource> AuditSources { get; set; }

    public virtual DbSet<AuditType> AuditTypes { get; set; }

    public virtual DbSet<AuditUser> AuditUsers { get; set; }

    public virtual DbSet<AuditUserAgent> AuditUserAgents { get; set; }

    public virtual DbSet<ExternalCommunication> ExternalCommunications { get; set; }

    public virtual DbSet<ExternalCommunicationRecipient> ExternalCommunicationRecipients { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AuditAccessType>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__AuditAcc__3213E83F1C1F5218");

            entity.ToTable("AuditAccessType", "Auditor");

            entity.HasIndex(e => e.name, "I_AuditAccessType_name");

            entity.HasIndex(e => e.name, "UQ__AuditAcc__72E12F1B900538AC").IsUnique();

            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<AuditEvent>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__AuditEve__3213E83FF7C06A15");

            entity.ToTable("AuditEvent", "Auditor");

            entity.HasIndex(e => e.auditAccessTypeId, "I_AuditEvent_auditAccessTypeId");

            entity.HasIndex(e => e.auditHostSystemId, "I_AuditEvent_auditHostSystemId");

            entity.HasIndex(e => e.auditModuleEntityId, "I_AuditEvent_auditModuleEntityId");

            entity.HasIndex(e => e.auditModuleId, "I_AuditEvent_auditModuleId");

            entity.HasIndex(e => e.auditResourceId, "I_AuditEvent_auditResourceId");

            entity.HasIndex(e => e.auditSessionId, "I_AuditEvent_auditSessionId");

            entity.HasIndex(e => e.auditSourceId, "I_AuditEvent_auditSourceId");

            entity.HasIndex(e => e.auditTypeId, "I_AuditEvent_auditTypeId");

            entity.HasIndex(e => e.auditUserAgentId, "I_AuditEvent_auditUserAgentId");

            entity.HasIndex(e => e.auditUserId, "I_AuditEvent_auditUserId");

            entity.HasIndex(e => e.startTime, "I_AuditEvent_startTime");

            entity.HasIndex(e => e.stopTime, "I_AuditEvent_stopTime");

            entity.Property(e => e.completedSuccessfully).HasDefaultValue(true);
            entity.Property(e => e.message).IsRequired();
            entity.Property(e => e.primaryKey).HasMaxLength(250);

            entity.HasOne(d => d.auditAccessType).WithMany(p => p.AuditEvents)
                .HasForeignKey(d => d.auditAccessTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.auditHostSystem).WithMany(p => p.AuditEvents)
                .HasForeignKey(d => d.auditHostSystemId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.auditModuleEntity).WithMany(p => p.AuditEvents)
                .HasForeignKey(d => d.auditModuleEntityId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.auditModule).WithMany(p => p.AuditEvents)
                .HasForeignKey(d => d.auditModuleId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.auditResource).WithMany(p => p.AuditEvents)
                .HasForeignKey(d => d.auditResourceId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.auditSession).WithMany(p => p.AuditEvents)
                .HasForeignKey(d => d.auditSessionId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.auditSource).WithMany(p => p.AuditEvents)
                .HasForeignKey(d => d.auditSourceId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.auditType).WithMany(p => p.AuditEvents)
                .HasForeignKey(d => d.auditTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.auditUserAgent).WithMany(p => p.AuditEvents)
                .HasForeignKey(d => d.auditUserAgentId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.auditUser).WithMany(p => p.AuditEvents)
                .HasForeignKey(d => d.auditUserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<AuditEventEntityState>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__AuditEve__3213E83F72A73E78");

            entity.ToTable("AuditEventEntityState", "Auditor");

            entity.HasIndex(e => e.auditEventId, "I_AuditEventEntityState_auditEventId");

            entity.HasOne(d => d.auditEvent).WithMany(p => p.AuditEventEntityStates)
                .HasForeignKey(d => d.auditEventId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<AuditEventErrorMessage>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__AuditEve__3213E83F4A497705");

            entity.ToTable("AuditEventErrorMessage", "Auditor");

            entity.HasIndex(e => e.auditEventId, "I_AuditEventErrorMessage_auditEventId");

            entity.Property(e => e.errorMessage).IsRequired();

            entity.HasOne(d => d.auditEvent).WithMany(p => p.AuditEventErrorMessages)
                .HasForeignKey(d => d.auditEventId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<AuditHostSystem>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__AuditHos__3213E83F250C14A0");

            entity.ToTable("AuditHostSystem", "Auditor");

            entity.HasIndex(e => e.name, "I_AuditHostSystem_name");

            entity.HasIndex(e => e.name, "UQ__AuditHos__72E12F1B3F1C7C0A").IsUnique();

            entity.Property(e => e.comments).HasMaxLength(1000);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<AuditModule>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__AuditMod__3213E83F6D9EE1D6");

            entity.ToTable("AuditModule", "Auditor");

            entity.HasIndex(e => e.name, "I_AuditModule_name");

            entity.HasIndex(e => e.name, "UQ__AuditMod__72E12F1B4D63C491").IsUnique();

            entity.Property(e => e.comments).HasMaxLength(1000);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<AuditModuleEntity>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__AuditMod__3213E83FFF2E05CA");

            entity.ToTable("AuditModuleEntity", "Auditor");

            entity.HasIndex(e => e.auditModuleId, "I_AuditModuleEntity_auditModuleId");

            entity.HasIndex(e => new { e.auditModuleId, e.name }, "I_AuditModuleEntity_auditModuleId_name");

            entity.Property(e => e.comments).HasMaxLength(1000);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.auditModule).WithMany(p => p.AuditModuleEntities)
                .HasForeignKey(d => d.auditModuleId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<AuditPlanB>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__AuditPla__3213E83F57B565BA");

            entity.ToTable("AuditPlanB", "Auditor");

            entity.HasIndex(e => e.startTime, "I_AuditPlanB_startTime");

            entity.HasIndex(e => e.stopTime, "I_AuditPlanB_stopTime");

            entity.Property(e => e.accessType).HasMaxLength(100);
            entity.Property(e => e.completedSuccessfully).HasDefaultValue(true);
            entity.Property(e => e.hostSystem).HasMaxLength(50);
            entity.Property(e => e.module).HasMaxLength(100);
            entity.Property(e => e.moduleEntity).HasMaxLength(100);
            entity.Property(e => e.primaryKey).HasMaxLength(250);
            entity.Property(e => e.resource).HasMaxLength(500);
            entity.Property(e => e.session).HasMaxLength(100);
            entity.Property(e => e.source).HasMaxLength(50);
            entity.Property(e => e.type).HasMaxLength(100);
            entity.Property(e => e.user).HasMaxLength(100);
            entity.Property(e => e.userAgent).HasMaxLength(100);
        });

        modelBuilder.Entity<AuditResource>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__AuditRes__3213E83F6C2AC43F");

            entity.ToTable("AuditResource", "Auditor");

            entity.HasIndex(e => e.name, "I_AuditResource_name");

            entity.HasIndex(e => e.name, "UQ__AuditRes__72E12F1B7F21F344").IsUnique();

            entity.Property(e => e.comments).HasMaxLength(1000);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(850);
        });

        modelBuilder.Entity<AuditSession>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__AuditSes__3213E83F4B1E43BE");

            entity.ToTable("AuditSession", "Auditor");

            entity.HasIndex(e => e.name, "I_AuditSession_name");

            entity.HasIndex(e => e.name, "UQ__AuditSes__72E12F1BC7287324").IsUnique();

            entity.Property(e => e.comments).HasMaxLength(1000);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<AuditSource>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__AuditSou__3213E83FDA1846F6");

            entity.ToTable("AuditSource", "Auditor");

            entity.HasIndex(e => e.name, "I_AuditSource_name");

            entity.HasIndex(e => e.name, "UQ__AuditSou__72E12F1B6A55B729").IsUnique();

            entity.Property(e => e.comments).HasMaxLength(1000);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<AuditType>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__AuditTyp__3213E83FDFCEAED3");

            entity.ToTable("AuditType", "Auditor");

            entity.HasIndex(e => e.name, "I_AuditType_name");

            entity.HasIndex(e => e.name, "UQ__AuditTyp__72E12F1B82D7F428").IsUnique();

            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<AuditUser>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__AuditUse__3213E83FFC6980BF");

            entity.ToTable("AuditUser", "Auditor");

            entity.HasIndex(e => e.name, "I_AuditUser_name");

            entity.HasIndex(e => e.name, "UQ__AuditUse__72E12F1BEC231A59").IsUnique();

            entity.Property(e => e.comments).HasMaxLength(1000);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<AuditUserAgent>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__AuditUse__3213E83FDA6542FE");

            entity.ToTable("AuditUserAgent", "Auditor");

            entity.HasIndex(e => e.name, "I_AuditUserAgent_name");

            entity.HasIndex(e => e.name, "UQ__AuditUse__72E12F1BCD8CA97E").IsUnique();

            entity.Property(e => e.comments).HasMaxLength(1000);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<ExternalCommunication>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__External__3213E83F4FC5B966");

            entity.ToTable("ExternalCommunication", "Auditor");

            entity.HasIndex(e => e.auditUserId, "I_ExternalCommunication_auditUserId");

            entity.Property(e => e.communicationType).HasMaxLength(100);
            entity.Property(e => e.completedSuccessfully).HasDefaultValue(true);
            entity.Property(e => e.subject).HasMaxLength(2000);

            entity.HasOne(d => d.auditUser).WithMany(p => p.ExternalCommunications).HasForeignKey(d => d.auditUserId);
        });

        modelBuilder.Entity<ExternalCommunicationRecipient>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__External__3213E83F3848D51A");

            entity.ToTable("ExternalCommunicationRecipient", "Auditor");

            entity.HasIndex(e => e.externalCommunicationId, "I_ExternalCommunicationRecipient_externalCommunicationId");

            entity.Property(e => e.recipient).HasMaxLength(100);
            entity.Property(e => e.type).HasMaxLength(50);

            entity.HasOne(d => d.externalCommunication).WithMany(p => p.ExternalCommunicationRecipients).HasForeignKey(d => d.externalCommunicationId);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}