// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Auditor.Database;

public partial class ExternalCommunication
{
    public int id { get; set; }

    public DateTime? timeStamp { get; set; }

    public int? auditUserId { get; set; }

    public string communicationType { get; set; }

    public string subject { get; set; }

    public string message { get; set; }

    public bool completedSuccessfully { get; set; }

    public string responseMessage { get; set; }

    public string exceptionText { get; set; }

    public virtual ICollection<ExternalCommunicationRecipient> ExternalCommunicationRecipients { get; set; } = new List<ExternalCommunicationRecipient>();

    public virtual AuditUser auditUser { get; set; }
}