// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Telemetry.Telemetry.Database;

public partial class TelemetryDiskHealth
{
    public int id { get; set; }

    public int telemetrySnapshotId { get; set; }

    public string driveName { get; set; }

    public string driveLabel { get; set; }

    public double? totalGB { get; set; }

    public double? freeGB { get; set; }

    public double? freePercent { get; set; }

    public string status { get; set; }

    public bool isApplicationDrive { get; set; }

    public virtual TelemetrySnapshot telemetrySnapshot { get; set; }
}