// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Foundation.Telemetry.Telemetry.Database;

public partial class TelemetryContext : DbContext
{
    public TelemetryContext(DbContextOptions<TelemetryContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TelemetryApplication> TelemetryApplications { get; set; }

    public virtual DbSet<TelemetryCollectionRun> TelemetryCollectionRuns { get; set; }

    public virtual DbSet<TelemetryDatabaseHealth> TelemetryDatabaseHealths { get; set; }

    public virtual DbSet<TelemetryDiskHealth> TelemetryDiskHealths { get; set; }

    public virtual DbSet<TelemetryErrorEvent> TelemetryErrorEvents { get; set; }

    public virtual DbSet<TelemetryLogError> TelemetryLogErrors { get; set; }

    public virtual DbSet<TelemetrySessionSnapshot> TelemetrySessionSnapshots { get; set; }

    public virtual DbSet<TelemetrySnapshot> TelemetrySnapshots { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TelemetryApplication>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Telemetr__3213E83FDCB5D556");

            entity.ToTable("TelemetryApplication", "Telemetry");

            entity.HasIndex(e => e.name, "I_TelemetryApplication_name");

            entity.HasIndex(e => e.name, "UQ__Telemetr__72E12F1B64AE4286").IsUnique();

            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.url).HasMaxLength(500);
        });

        modelBuilder.Entity<TelemetryCollectionRun>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Telemetr__3213E83FB7F7E6E2");

            entity.ToTable("TelemetryCollectionRun", "Telemetry");

            entity.HasIndex(e => e.startTime, "I_TelemetryCollectionRun_startTime");
        });

        modelBuilder.Entity<TelemetryDatabaseHealth>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Telemetr__3213E83F82A77562");

            entity.ToTable("TelemetryDatabaseHealth", "Telemetry");

            entity.HasIndex(e => e.telemetrySnapshotId, "I_TelemetryDatabaseHealth_telemetrySnapshotId");

            entity.Property(e => e.databaseName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.isConnected).HasDefaultValue(true);
            entity.Property(e => e.provider).HasMaxLength(100);
            entity.Property(e => e.server).HasMaxLength(250);
            entity.Property(e => e.status).HasMaxLength(50);

            entity.HasOne(d => d.telemetrySnapshot).WithMany(p => p.TelemetryDatabaseHealths)
                .HasForeignKey(d => d.telemetrySnapshotId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TelemetryDiskHealth>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Telemetr__3213E83F1C45FDC3");

            entity.ToTable("TelemetryDiskHealth", "Telemetry");

            entity.HasIndex(e => e.telemetrySnapshotId, "I_TelemetryDiskHealth_telemetrySnapshotId");

            entity.Property(e => e.driveLabel).HasMaxLength(100);
            entity.Property(e => e.driveName)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.status).HasMaxLength(50);

            entity.HasOne(d => d.telemetrySnapshot).WithMany(p => p.TelemetryDiskHealths)
                .HasForeignKey(d => d.telemetrySnapshotId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TelemetryErrorEvent>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Telemetr__3213E83FAE12F6BF");

            entity.ToTable("TelemetryErrorEvent", "Telemetry");

            entity.HasIndex(e => e.occurredAt, "I_TelemetryErrorEvent_occurredAt");

            entity.HasIndex(e => e.telemetryApplicationId, "I_TelemetryErrorEvent_telemetryApplicationId");

            entity.HasIndex(e => e.telemetrySnapshotId, "I_TelemetryErrorEvent_telemetrySnapshotId");

            entity.Property(e => e.auditTypeName).HasMaxLength(100);
            entity.Property(e => e.entityName).HasMaxLength(100);
            entity.Property(e => e.moduleName).HasMaxLength(100);
            entity.Property(e => e.userName).HasMaxLength(500);

            entity.HasOne(d => d.telemetryApplication).WithMany(p => p.TelemetryErrorEvents)
                .HasForeignKey(d => d.telemetryApplicationId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.telemetrySnapshot).WithMany(p => p.TelemetryErrorEvents).HasForeignKey(d => d.telemetrySnapshotId);
        });

        modelBuilder.Entity<TelemetryLogError>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Telemetr__3213E83FE9B08E75");

            entity.ToTable("TelemetryLogError", "Telemetry");

            entity.HasIndex(e => e.capturedAt, "I_TelemetryLogError_capturedAt");

            entity.HasIndex(e => e.telemetryApplicationId, "I_TelemetryLogError_telemetryApplicationId");

            entity.HasIndex(e => e.telemetrySnapshotId, "I_TelemetryLogError_telemetrySnapshotId");

            entity.Property(e => e.level).HasMaxLength(50);
            entity.Property(e => e.logFileName).HasMaxLength(250);

            entity.HasOne(d => d.telemetryApplication).WithMany(p => p.TelemetryLogErrors)
                .HasForeignKey(d => d.telemetryApplicationId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.telemetrySnapshot).WithMany(p => p.TelemetryLogErrors).HasForeignKey(d => d.telemetrySnapshotId);
        });

        modelBuilder.Entity<TelemetrySessionSnapshot>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Telemetr__3213E83F3EB0AAAB");

            entity.ToTable("TelemetrySessionSnapshot", "Telemetry");

            entity.HasIndex(e => e.telemetrySnapshotId, "I_TelemetrySessionSnapshot_telemetrySnapshotId");

            entity.HasOne(d => d.telemetrySnapshot).WithMany(p => p.TelemetrySessionSnapshots)
                .HasForeignKey(d => d.telemetrySnapshotId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TelemetrySnapshot>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Telemetr__3213E83FEC4F1E83");

            entity.ToTable("TelemetrySnapshot", "Telemetry");

            entity.HasIndex(e => e.collectedAt, "I_TelemetrySnapshot_collectedAt");

            entity.HasIndex(e => e.telemetryApplicationId, "I_TelemetrySnapshot_telemetryApplicationId");

            entity.HasIndex(e => new { e.telemetryApplicationId, e.collectedAt }, "I_TelemetrySnapshot_telemetryApplicationId_collectedAt");

            entity.HasIndex(e => e.telemetryCollectionRunId, "I_TelemetrySnapshot_telemetryCollectionRunId");

            entity.Property(e => e.dotNetVersion).HasMaxLength(50);
            entity.Property(e => e.isOnline).HasDefaultValue(true);
            entity.Property(e => e.machineName).HasMaxLength(100);

            entity.HasOne(d => d.telemetryApplication).WithMany(p => p.TelemetrySnapshots)
                .HasForeignKey(d => d.telemetryApplicationId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.telemetryCollectionRun).WithMany(p => p.TelemetrySnapshots)
                .HasForeignKey(d => d.telemetryCollectionRunId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}