//
// User Sessions Tab Component
//
// Displays active sessions for a user and provides session revocation capabilities.
// Follows the same patterns as user-activity-tab for consistency.
//
// AI-generated: This component was generated by AI assistant to integrate
// session management into the user detail component.
//

import { Component, Input, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { SecurityUserData, SecurityUserService } from '../../../security-data-services/security-user.service';
import { UserSessionManagementService, UserSessionInfo } from '../../../services/user-session-management.service';
import { SessionActionDialogComponent, SessionActionResult } from '../../../services/session-action-dialog/session-action-dialog.component';
import { AlertService, MessageSeverity } from '../../../services/alert.service';


@Component({
    selector: 'app-user-sessions-tab',
    templateUrl: './user-sessions-tab.component.html',
    styleUrls: ['./user-sessions-tab.component.scss']
})
export class UserSessionsTabComponent implements OnInit, OnChanges {

    @Input() user: SecurityUserData | null = null;

    //
    // Sessions data
    //
    public sessions: UserSessionInfo[] = [];
    public loading: boolean = false;
    public error: string | null = null;

    //
    // Action state
    //
    public actionInProgress: boolean = false;


    constructor(
        private userSessionService: UserSessionManagementService,
        private securityUserService: SecurityUserService,
        private modalService: NgbModal,
        private alertService: AlertService
    ) { }


    ngOnInit(): void {
        this.loadSessions();
    }


    ngOnChanges(changes: SimpleChanges): void {
        if (changes['user'] && !changes['user'].firstChange) {
            this.loadSessions();
        }
    }


    //
    // Data Loading
    //
    public loadSessions(): void {
        if (!this.user) return;

        this.loading = true;
        this.error = null;

        this.userSessionService.getUserSessions(Number(this.user.id)).subscribe({
            next: (data) => {
                //
                // Sort by session start descending (most recent first)
                //
                this.sessions = (data ?? []).sort((a, b) => {
                    const aTime = new Date(a.sessionStart).getTime();
                    const bTime = new Date(b.sessionStart).getTime();
                    return bTime - aTime;
                });
                this.loading = false;
            },
            error: (err) => {
                console.error('Failed to load sessions', err);
                this.sessions = [];
                this.error = 'Failed to load sessions. You may not have permission to view this information.';
                this.loading = false;
            }
        });
    }


    //
    // Session Revocation
    //
    public revokeSession(session: UserSessionInfo): void {
        if (this.actionInProgress) return;

        //
        // Open the session action dialog
        //
        const modalRef = this.modalService.open(SessionActionDialogComponent, {
            centered: true,
            size: 'md'
        });
        modalRef.componentInstance.title = 'Revoke Session';
        modalRef.componentInstance.username = session.displayName || session.username;
        modalRef.componentInstance.showLockOption = false;

        modalRef.result.then(
            (result: SessionActionResult) => {
                if (result.confirmed === true) {
                    this.performRevoke(session, result.reason);
                }
            },
            () => { }
        );
    }


    private performRevoke(session: UserSessionInfo, reason: string): void {
        this.actionInProgress = true;

        this.userSessionService.revokeSession(session.sessionId, reason).subscribe({
            next: (response) => {
                if (response.success === true) {
                    //
                    // Remove the session from the list
                    //
                    this.sessions = this.sessions.filter(s => s.sessionId !== session.sessionId);
                    this.alertService.showMessage('Success', 'Session revoked successfully', MessageSeverity.success);
                } else {
                    this.alertService.showMessage('Error', response.message || 'Failed to revoke session', MessageSeverity.error);
                }
                this.actionInProgress = false;
            },
            error: (err) => {
                console.error('Failed to revoke session', err);
                this.alertService.showMessage('Error', 'Failed to revoke session', MessageSeverity.error);
                this.actionInProgress = false;
            }
        });
    }


    public revokeAllSessions(): void {
        if (!this.user || this.actionInProgress || this.sessions.length === 0) return;

        //
        // Open the session action dialog
        //
        const modalRef = this.modalService.open(SessionActionDialogComponent, {
            centered: true,
            size: 'md'
        });
        modalRef.componentInstance.title = 'Revoke All Sessions';
        modalRef.componentInstance.username = this.getUserDisplayName();
        modalRef.componentInstance.showLockOption = true;

        modalRef.result.then(
            (result: SessionActionResult) => {
                if (result.confirmed === true) {
                    if (result.action === 'revoke-and-lock') {
                        this.performRevokeAllAndLock(result.reason);
                    } else {
                        this.performRevokeAll(result.reason);
                    }
                }
            },
            () => { }
        );
    }


    private performRevokeAll(reason: string): void {
        if (!this.user) return;

        this.actionInProgress = true;

        this.userSessionService.revokeAllUserSessions(Number(this.user.id), reason).subscribe({
            next: (response) => {
                if (response.success === true) {
                    this.sessions = [];
                    this.alertService.showMessage(
                        'Success',
                        `Revoked ${response.revokedCount} session(s)`,
                        MessageSeverity.success
                    );
                } else {
                    this.alertService.showMessage('Error', response.message || 'Failed to revoke sessions', MessageSeverity.error);
                }
                this.actionInProgress = false;
            },
            error: (err) => {
                console.error('Failed to revoke all sessions', err);
                this.alertService.showMessage('Error', 'Failed to revoke sessions', MessageSeverity.error);
                this.actionInProgress = false;
            }
        });
    }


    private performRevokeAllAndLock(reason: string): void {
        if (!this.user) return;

        this.actionInProgress = true;

        this.userSessionService.revokeAllAndLockAccount(Number(this.user.id), reason).subscribe({
            next: (response) => {
                if (response.success === true) {
                    this.sessions = [];
                    this.alertService.showMessage(
                        'Success',
                        `Revoked ${response.revokedCount} session(s) and locked account`,
                        MessageSeverity.success
                    );
                } else {
                    this.alertService.showMessage('Error', response.message || 'Failed to revoke and lock', MessageSeverity.error);
                }
                this.actionInProgress = false;
            },
            error: (err) => {
                console.error('Failed to revoke and lock', err);
                this.alertService.showMessage('Error', 'Failed to revoke and lock account', MessageSeverity.error);
                this.actionInProgress = false;
            }
        });
    }


    //
    // Display helpers
    //
    public getUserDisplayName(): string {
        if (!this.user) return '';
        const parts = [this.user.firstName, this.user.lastName].filter(p => p);
        return parts.length > 0 ? parts.join(' ') : this.user.accountName;
    }


    public getActiveSessions(): UserSessionInfo[] {
        return this.sessions.filter(s => s.isActive === true && s.isExpired === false);
    }


    public formatDate(dateValue: string | Date | null): string {
        if (dateValue == null) return '—';
        return new Date(dateValue).toLocaleString();
    }


    public formatRelativeTime(dateValue: string | Date | null): string {
        if (dateValue == null) return 'Never';

        const date = new Date(dateValue);
        const now = new Date();
        const diffMs = now.getTime() - date.getTime();
        const diffMins = Math.floor(diffMs / 60000);
        const diffHours = Math.floor(diffMs / 3600000);
        const diffDays = Math.floor(diffMs / 86400000);

        if (diffMins < 1) return 'Just now';
        if (diffMins < 60) return `${diffMins}m ago`;
        if (diffHours < 24) return `${diffHours}h ago`;
        if (diffDays < 7) return `${diffDays}d ago`;

        return date.toLocaleDateString();
    }


    public getLoginMethodIcon(method: string | null | undefined): string {
        if (method == null) return 'fa-right-to-bracket';

        const lowerMethod = method.toLowerCase();

        if (lowerMethod.includes('microsoft')) return 'fa-microsoft';
        if (lowerMethod.includes('google')) return 'fa-google';
        if (lowerMethod.includes('refresh')) return 'fa-rotate';
        if (lowerMethod.includes('password')) return 'fa-key';

        return 'fa-right-to-bracket';
    }


    public getLoginMethodBadgeClass(method: string | null | undefined): string {
        if (method == null) return 'bg-secondary';

        const lowerMethod = method.toLowerCase();

        if (lowerMethod.includes('microsoft')) return 'bg-primary';
        if (lowerMethod.includes('google')) return 'bg-danger';
        if (lowerMethod.includes('refresh')) return 'bg-info';
        if (lowerMethod.includes('password')) return 'bg-success';

        return 'bg-secondary';
    }


    //
    // Permissions
    //
    public userIsSecurityUserWriter(): boolean {
        return this.securityUserService.userIsSecuritySecurityUserWriter();
    }
}
