// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Community.Database;

public partial class Announcement
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string title { get; set; }

    public string body { get; set; }

    public string severity { get; set; }

    public DateTime startDate { get; set; }

    public DateTime? endDate { get; set; }

    public bool isPinned { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<AnnouncementChangeHistory> AnnouncementChangeHistories { get; set; } = new List<AnnouncementChangeHistory>();
}