// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Foundation.Community.Database;

public partial class CommunityContext : DbContext
{
    public CommunityContext(DbContextOptions<CommunityContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Announcement> Announcements { get; set; }

    public virtual DbSet<AnnouncementChangeHistory> AnnouncementChangeHistories { get; set; }

    public virtual DbSet<ContactSubmission> ContactSubmissions { get; set; }

    public virtual DbSet<DocumentDownload> DocumentDownloads { get; set; }

    public virtual DbSet<GalleryAlbum> GalleryAlbums { get; set; }

    public virtual DbSet<GalleryImage> GalleryImages { get; set; }

    public virtual DbSet<MediaAsset> MediaAssets { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<MenuItem> MenuItems { get; set; }

    public virtual DbSet<Page> Pages { get; set; }

    public virtual DbSet<PageChangeHistory> PageChangeHistories { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<PostCategory> PostCategories { get; set; }

    public virtual DbSet<PostChangeHistory> PostChangeHistories { get; set; }

    public virtual DbSet<PostTag> PostTags { get; set; }

    public virtual DbSet<PostTagAssignment> PostTagAssignments { get; set; }

    public virtual DbSet<SiteSetting> SiteSettings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Announcement>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Announce__3213E83F9E395E83");

            entity.ToTable("Announcement", "Community");

            entity.HasIndex(e => e.Active, "I_Announcement_active");

            entity.HasIndex(e => e.Deleted, "I_Announcement_deleted");

            entity.HasIndex(e => e.ObjectGuid, "UQ__Announce__3E543F949B263235").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasColumnName("active");
            entity.Property(e => e.Body).HasColumnName("body");
            entity.Property(e => e.Deleted).HasColumnName("deleted");
            entity.Property(e => e.EndDate).HasColumnName("endDate");
            entity.Property(e => e.IsPinned).HasColumnName("isPinned");
            entity.Property(e => e.ObjectGuid).HasColumnName("objectGuid");
            entity.Property(e => e.Severity)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("info")
                .HasColumnName("severity");
            entity.Property(e => e.StartDate).HasColumnName("startDate");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("title");
            entity.Property(e => e.VersionNumber)
                .HasDefaultValue(1)
                .HasColumnName("versionNumber");
        });

        modelBuilder.Entity<AnnouncementChangeHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Announce__3213E83F0285A01D");

            entity.ToTable("AnnouncementChangeHistory", "Community");

            entity.HasIndex(e => e.AnnouncementId, "I_AnnouncementChangeHistory_announcementId");

            entity.HasIndex(e => e.TimeStamp, "I_AnnouncementChangeHistory_timeStamp");

            entity.HasIndex(e => e.UserId, "I_AnnouncementChangeHistory_userId");

            entity.HasIndex(e => e.VersionNumber, "I_AnnouncementChangeHistory_versionNumber");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnnouncementId).HasColumnName("announcementId");
            entity.Property(e => e.Data)
                .IsRequired()
                .HasColumnName("data");
            entity.Property(e => e.TimeStamp).HasColumnName("timeStamp");
            entity.Property(e => e.UserId).HasColumnName("userId");
            entity.Property(e => e.VersionNumber).HasColumnName("versionNumber");

            entity.HasOne(d => d.Announcement).WithMany(p => p.AnnouncementChangeHistories)
                .HasForeignKey(d => d.AnnouncementId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ContactSubmission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ContactS__3213E83FBD69A54A");

            entity.ToTable("ContactSubmission", "Community");

            entity.HasIndex(e => e.Active, "I_ContactSubmission_active");

            entity.HasIndex(e => e.Deleted, "I_ContactSubmission_deleted");

            entity.HasIndex(e => e.ObjectGuid, "UQ__ContactS__3E543F94730734AC").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasColumnName("active");
            entity.Property(e => e.AdminNotes)
                .HasMaxLength(500)
                .HasColumnName("adminNotes");
            entity.Property(e => e.Deleted).HasColumnName("deleted");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("email");
            entity.Property(e => e.IsArchived).HasColumnName("isArchived");
            entity.Property(e => e.IsRead).HasColumnName("isRead");
            entity.Property(e => e.Message)
                .IsRequired()
                .HasColumnName("message");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.ObjectGuid).HasColumnName("objectGuid");
            entity.Property(e => e.Subject)
                .HasMaxLength(250)
                .HasColumnName("subject");
            entity.Property(e => e.SubmittedDate).HasColumnName("submittedDate");
        });

        modelBuilder.Entity<DocumentDownload>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Document__3213E83F28F63045");

            entity.ToTable("DocumentDownload", "Community");

            entity.HasIndex(e => e.Active, "I_DocumentDownload_active");

            entity.HasIndex(e => e.Deleted, "I_DocumentDownload_deleted");

            entity.HasIndex(e => e.ObjectGuid, "UQ__Document__3E543F9425889F19").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasColumnName("active");
            entity.Property(e => e.CategoryName)
                .HasMaxLength(100)
                .HasColumnName("categoryName");
            entity.Property(e => e.Deleted).HasColumnName("deleted");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DocumentDate).HasColumnName("documentDate");
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("fileName");
            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("filePath");
            entity.Property(e => e.FileSizeBytes).HasColumnName("fileSizeBytes");
            entity.Property(e => e.IsPublished)
                .HasDefaultValue(true)
                .HasColumnName("isPublished");
            entity.Property(e => e.MimeType)
                .HasMaxLength(100)
                .HasColumnName("mimeType");
            entity.Property(e => e.ObjectGuid).HasColumnName("objectGuid");
            entity.Property(e => e.Sequence).HasColumnName("sequence");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("title");
        });

        modelBuilder.Entity<GalleryAlbum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__GalleryA__3213E83FF2E97204");

            entity.ToTable("GalleryAlbum", "Community");

            entity.HasIndex(e => e.Active, "I_GalleryAlbum_active");

            entity.HasIndex(e => e.Deleted, "I_GalleryAlbum_deleted");

            entity.HasIndex(e => e.Slug, "I_GalleryAlbum_slug").IsUnique();

            entity.HasIndex(e => e.ObjectGuid, "UQ__GalleryA__3E543F94AD9584F0").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasColumnName("active");
            entity.Property(e => e.CoverImageUrl)
                .HasMaxLength(500)
                .HasColumnName("coverImageUrl");
            entity.Property(e => e.Deleted).HasColumnName("deleted");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsPublished)
                .HasDefaultValue(true)
                .HasColumnName("isPublished");
            entity.Property(e => e.ObjectGuid).HasColumnName("objectGuid");
            entity.Property(e => e.Sequence).HasColumnName("sequence");
            entity.Property(e => e.Slug)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("slug");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("title");
        });

        modelBuilder.Entity<GalleryImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__GalleryI__3213E83FCE1E178A");

            entity.ToTable("GalleryImage", "Community");

            entity.HasIndex(e => e.Active, "I_GalleryImage_active");

            entity.HasIndex(e => e.Deleted, "I_GalleryImage_deleted");

            entity.HasIndex(e => e.GalleryAlbumId, "I_GalleryImage_galleryAlbumId");

            entity.HasIndex(e => e.ObjectGuid, "UQ__GalleryI__3E543F942ABD15FD").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasColumnName("active");
            entity.Property(e => e.AltText)
                .HasMaxLength(250)
                .HasColumnName("altText");
            entity.Property(e => e.Caption)
                .HasMaxLength(500)
                .HasColumnName("caption");
            entity.Property(e => e.Deleted).HasColumnName("deleted");
            entity.Property(e => e.GalleryAlbumId).HasColumnName("galleryAlbumId");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("imageUrl");
            entity.Property(e => e.ObjectGuid).HasColumnName("objectGuid");
            entity.Property(e => e.Sequence).HasColumnName("sequence");

            entity.HasOne(d => d.GalleryAlbum).WithMany(p => p.GalleryImages)
                .HasForeignKey(d => d.GalleryAlbumId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<MediaAsset>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MediaAss__3213E83FEAF4B99C");

            entity.ToTable("MediaAsset", "Community");

            entity.HasIndex(e => e.Active, "I_MediaAsset_active");

            entity.HasIndex(e => e.Deleted, "I_MediaAsset_deleted");

            entity.HasIndex(e => e.ObjectGuid, "UQ__MediaAss__3E543F940736084A").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasColumnName("active");
            entity.Property(e => e.AltText)
                .HasMaxLength(250)
                .HasColumnName("altText");
            entity.Property(e => e.Caption)
                .HasMaxLength(500)
                .HasColumnName("caption");
            entity.Property(e => e.Deleted).HasColumnName("deleted");
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("fileName");
            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("filePath");
            entity.Property(e => e.FileSizeBytes).HasColumnName("fileSizeBytes");
            entity.Property(e => e.ImageHeight).HasColumnName("imageHeight");
            entity.Property(e => e.ImageWidth).HasColumnName("imageWidth");
            entity.Property(e => e.MimeType)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("mimeType");
            entity.Property(e => e.ObjectGuid).HasColumnName("objectGuid");
        });

        modelBuilder.Entity<Menu>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Menu__3213E83F4ED75A3C");

            entity.ToTable("Menu", "Community");

            entity.HasIndex(e => e.Active, "I_Menu_active");

            entity.HasIndex(e => e.Deleted, "I_Menu_deleted");

            entity.HasIndex(e => e.Name, "I_Menu_name");

            entity.HasIndex(e => e.ObjectGuid, "UQ__Menu__3E543F94BB02489A").IsUnique();

            entity.HasIndex(e => e.Name, "UQ__Menu__72E12F1B017F1AF8").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasColumnName("active");
            entity.Property(e => e.Deleted).HasColumnName("deleted");
            entity.Property(e => e.Location)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("location");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.ObjectGuid).HasColumnName("objectGuid");
        });

        modelBuilder.Entity<MenuItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MenuItem__3213E83F3929F0BF");

            entity.ToTable("MenuItem", "Community");

            entity.HasIndex(e => e.Active, "I_MenuItem_active");

            entity.HasIndex(e => e.Deleted, "I_MenuItem_deleted");

            entity.HasIndex(e => e.MenuId, "I_MenuItem_menuId");

            entity.HasIndex(e => e.PageId, "I_MenuItem_pageId");

            entity.HasIndex(e => e.ParentMenuItemId, "I_MenuItem_parentMenuItemId");

            entity.HasIndex(e => e.ObjectGuid, "UQ__MenuItem__3E543F9417168DD0").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasColumnName("active");
            entity.Property(e => e.Deleted).HasColumnName("deleted");
            entity.Property(e => e.IconClass)
                .HasMaxLength(50)
                .HasColumnName("iconClass");
            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("label");
            entity.Property(e => e.MenuId).HasColumnName("menuId");
            entity.Property(e => e.ObjectGuid).HasColumnName("objectGuid");
            entity.Property(e => e.OpenInNewTab).HasColumnName("openInNewTab");
            entity.Property(e => e.PageId).HasColumnName("pageId");
            entity.Property(e => e.ParentMenuItemId).HasColumnName("parentMenuItemId");
            entity.Property(e => e.Sequence).HasColumnName("sequence");
            entity.Property(e => e.Url)
                .HasMaxLength(500)
                .HasColumnName("url");

            entity.HasOne(d => d.Menu).WithMany(p => p.MenuItems)
                .HasForeignKey(d => d.MenuId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Page).WithMany(p => p.MenuItems).HasForeignKey(d => d.PageId);

            entity.HasOne(d => d.ParentMenuItem).WithMany(p => p.InverseParentMenuItem).HasForeignKey(d => d.ParentMenuItemId);
        });

        modelBuilder.Entity<Page>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Page__3213E83FD0589E44");

            entity.ToTable("Page", "Community");

            entity.HasIndex(e => e.Active, "I_Page_active");

            entity.HasIndex(e => e.Deleted, "I_Page_deleted");

            entity.HasIndex(e => e.Slug, "I_Page_slug").IsUnique();

            entity.HasIndex(e => e.ObjectGuid, "UQ__Page__3E543F941FB74ED9").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasColumnName("active");
            entity.Property(e => e.Body).HasColumnName("body");
            entity.Property(e => e.Deleted).HasColumnName("deleted");
            entity.Property(e => e.FeaturedImageUrl)
                .HasMaxLength(500)
                .HasColumnName("featuredImageUrl");
            entity.Property(e => e.IsPublished).HasColumnName("isPublished");
            entity.Property(e => e.MetaDescription)
                .HasMaxLength(500)
                .HasColumnName("metaDescription");
            entity.Property(e => e.ObjectGuid).HasColumnName("objectGuid");
            entity.Property(e => e.PublishedDate).HasColumnName("publishedDate");
            entity.Property(e => e.Slug)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("slug");
            entity.Property(e => e.SortOrder)
                .HasDefaultValue(0)
                .HasColumnName("sortOrder");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("title");
            entity.Property(e => e.VersionNumber)
                .HasDefaultValue(1)
                .HasColumnName("versionNumber");
        });

        modelBuilder.Entity<PageChangeHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PageChan__3213E83F1A52D592");

            entity.ToTable("PageChangeHistory", "Community");

            entity.HasIndex(e => e.PageId, "I_PageChangeHistory_pageId");

            entity.HasIndex(e => e.TimeStamp, "I_PageChangeHistory_timeStamp");

            entity.HasIndex(e => e.UserId, "I_PageChangeHistory_userId");

            entity.HasIndex(e => e.VersionNumber, "I_PageChangeHistory_versionNumber");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Data)
                .IsRequired()
                .HasColumnName("data");
            entity.Property(e => e.PageId).HasColumnName("pageId");
            entity.Property(e => e.TimeStamp).HasColumnName("timeStamp");
            entity.Property(e => e.UserId).HasColumnName("userId");
            entity.Property(e => e.VersionNumber).HasColumnName("versionNumber");

            entity.HasOne(d => d.Page).WithMany(p => p.PageChangeHistories)
                .HasForeignKey(d => d.PageId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Post__3213E83FF6D1781D");

            entity.ToTable("Post", "Community");

            entity.HasIndex(e => e.Active, "I_Post_active");

            entity.HasIndex(e => e.Deleted, "I_Post_deleted");

            entity.HasIndex(e => e.PostCategoryId, "I_Post_postCategoryId");

            entity.HasIndex(e => e.Slug, "I_Post_slug").IsUnique();

            entity.HasIndex(e => e.Title, "I_Post_title");

            entity.HasIndex(e => e.ObjectGuid, "UQ__Post__3E543F945C1813EB").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasColumnName("active");
            entity.Property(e => e.AuthorName)
                .HasMaxLength(100)
                .HasColumnName("authorName");
            entity.Property(e => e.Body).HasColumnName("body");
            entity.Property(e => e.Deleted).HasColumnName("deleted");
            entity.Property(e => e.Excerpt)
                .HasMaxLength(500)
                .HasColumnName("excerpt");
            entity.Property(e => e.FeaturedImageUrl)
                .HasMaxLength(500)
                .HasColumnName("featuredImageUrl");
            entity.Property(e => e.IsFeatured).HasColumnName("isFeatured");
            entity.Property(e => e.IsPublished).HasColumnName("isPublished");
            entity.Property(e => e.MetaDescription)
                .HasMaxLength(500)
                .HasColumnName("metaDescription");
            entity.Property(e => e.ObjectGuid).HasColumnName("objectGuid");
            entity.Property(e => e.PostCategoryId).HasColumnName("postCategoryId");
            entity.Property(e => e.PublishedDate).HasColumnName("publishedDate");
            entity.Property(e => e.Slug)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("slug");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("title");
            entity.Property(e => e.VersionNumber)
                .HasDefaultValue(1)
                .HasColumnName("versionNumber");

            entity.HasOne(d => d.PostCategory).WithMany(p => p.Posts).HasForeignKey(d => d.PostCategoryId);
        });

        modelBuilder.Entity<PostCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PostCate__3213E83FF14936AF");

            entity.ToTable("PostCategory", "Community");

            entity.HasIndex(e => e.Active, "I_PostCategory_active");

            entity.HasIndex(e => e.Deleted, "I_PostCategory_deleted");

            entity.HasIndex(e => e.Name, "I_PostCategory_name");

            entity.HasIndex(e => e.Slug, "I_PostCategory_slug").IsUnique();

            entity.HasIndex(e => e.ObjectGuid, "UQ__PostCate__3E543F94CE7A671E").IsUnique();

            entity.HasIndex(e => e.Name, "UQ__PostCate__72E12F1B493850A3").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasColumnName("active");
            entity.Property(e => e.Deleted).HasColumnName("deleted");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.ObjectGuid).HasColumnName("objectGuid");
            entity.Property(e => e.Sequence).HasColumnName("sequence");
            entity.Property(e => e.Slug)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("slug");
        });

        modelBuilder.Entity<PostChangeHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PostChan__3213E83F15351C37");

            entity.ToTable("PostChangeHistory", "Community");

            entity.HasIndex(e => e.PostId, "I_PostChangeHistory_postId");

            entity.HasIndex(e => e.TimeStamp, "I_PostChangeHistory_timeStamp");

            entity.HasIndex(e => e.UserId, "I_PostChangeHistory_userId");

            entity.HasIndex(e => e.VersionNumber, "I_PostChangeHistory_versionNumber");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Data)
                .IsRequired()
                .HasColumnName("data");
            entity.Property(e => e.PostId).HasColumnName("postId");
            entity.Property(e => e.TimeStamp).HasColumnName("timeStamp");
            entity.Property(e => e.UserId).HasColumnName("userId");
            entity.Property(e => e.VersionNumber).HasColumnName("versionNumber");

            entity.HasOne(d => d.Post).WithMany(p => p.PostChangeHistories)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<PostTag>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PostTag__3213E83F7DA3563D");

            entity.ToTable("PostTag", "Community");

            entity.HasIndex(e => e.Active, "I_PostTag_active");

            entity.HasIndex(e => e.Deleted, "I_PostTag_deleted");

            entity.HasIndex(e => e.Name, "I_PostTag_name");

            entity.HasIndex(e => e.Slug, "I_PostTag_slug").IsUnique();

            entity.HasIndex(e => e.ObjectGuid, "UQ__PostTag__3E543F94E2379538").IsUnique();

            entity.HasIndex(e => e.Name, "UQ__PostTag__72E12F1BE31FDCEE").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasColumnName("active");
            entity.Property(e => e.Deleted).HasColumnName("deleted");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.ObjectGuid).HasColumnName("objectGuid");
            entity.Property(e => e.Slug)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("slug");
        });

        modelBuilder.Entity<PostTagAssignment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PostTagA__3213E83F411A2B83");

            entity.ToTable("PostTagAssignment", "Community");

            entity.HasIndex(e => e.Active, "I_PostTagAssignment_active");

            entity.HasIndex(e => e.Deleted, "I_PostTagAssignment_deleted");

            entity.HasIndex(e => e.PostId, "I_PostTagAssignment_postId");

            entity.HasIndex(e => e.PostTagId, "I_PostTagAssignment_postTagId");

            entity.HasIndex(e => new { e.PostId, e.PostTagId }, "UC_PostTagAssignment_postId_postTagId").IsUnique();

            entity.HasIndex(e => e.ObjectGuid, "UQ__PostTagA__3E543F9434E862C0").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasColumnName("active");
            entity.Property(e => e.Deleted).HasColumnName("deleted");
            entity.Property(e => e.ObjectGuid).HasColumnName("objectGuid");
            entity.Property(e => e.PostId).HasColumnName("postId");
            entity.Property(e => e.PostTagId).HasColumnName("postTagId");

            entity.HasOne(d => d.Post).WithMany(p => p.PostTagAssignments)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.PostTag).WithMany(p => p.PostTagAssignments)
                .HasForeignKey(d => d.PostTagId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<SiteSetting>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SiteSett__3213E83FA717D89D");

            entity.ToTable("SiteSetting", "Community");

            entity.HasIndex(e => e.Active, "I_SiteSetting_active");

            entity.HasIndex(e => e.Deleted, "I_SiteSetting_deleted");

            entity.HasIndex(e => e.SettingKey, "I_SiteSetting_settingKey").IsUnique();

            entity.HasIndex(e => e.ObjectGuid, "UQ__SiteSett__3E543F9477DFF4B2").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true)
                .HasColumnName("active");
            entity.Property(e => e.Deleted).HasColumnName("deleted");
            entity.Property(e => e.Description)
                .HasMaxLength(250)
                .HasColumnName("description");
            entity.Property(e => e.ObjectGuid).HasColumnName("objectGuid");
            entity.Property(e => e.SettingGroup)
                .HasMaxLength(50)
                .HasColumnName("settingGroup");
            entity.Property(e => e.SettingKey)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("settingKey");
            entity.Property(e => e.SettingValue).HasColumnName("settingValue");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}