// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Foundation.Community.Database;

public partial class CommunityContext : DbContext
{
    public CommunityContext(DbContextOptions<CommunityContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Announcement> Announcements { get; set; }

    public virtual DbSet<AnnouncementChangeHistory> AnnouncementChangeHistories { get; set; }

    public virtual DbSet<ContactSubmission> ContactSubmissions { get; set; }

    public virtual DbSet<DocumentDownload> DocumentDownloads { get; set; }

    public virtual DbSet<GalleryAlbum> GalleryAlbums { get; set; }

    public virtual DbSet<GalleryImage> GalleryImages { get; set; }

    public virtual DbSet<MediaAsset> MediaAssets { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<MenuItem> MenuItems { get; set; }

    public virtual DbSet<Page> Pages { get; set; }

    public virtual DbSet<PageChangeHistory> PageChangeHistories { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<PostCategory> PostCategories { get; set; }

    public virtual DbSet<PostChangeHistory> PostChangeHistories { get; set; }

    public virtual DbSet<PostTag> PostTags { get; set; }

    public virtual DbSet<PostTagAssignment> PostTagAssignments { get; set; }

    public virtual DbSet<SiteSetting> SiteSettings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Announcement>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Announce__3213E83F358CA734");

            entity.ToTable("Announcement", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_Announcement_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_Announcement_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_Announcement_tenantGuid_deleted");

            entity.HasIndex(e => e.objectGuid, "UQ__Announce__3E543F94229E0CC6").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.severity)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("info");
            entity.Property(e => e.title)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);
        });

        modelBuilder.Entity<AnnouncementChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Announce__3213E83F3F94E511");

            entity.ToTable("AnnouncementChangeHistory", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_AnnouncementChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.announcementId }, "I_AnnouncementChangeHistory_tenantGuid_announcementId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_AnnouncementChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_AnnouncementChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_AnnouncementChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.announcement).WithMany(p => p.AnnouncementChangeHistories)
                .HasForeignKey(d => d.announcementId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ContactSubmission>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__ContactS__3213E83F02CD745F");

            entity.ToTable("ContactSubmission", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_ContactSubmission_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_ContactSubmission_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_ContactSubmission_tenantGuid_deleted");

            entity.HasIndex(e => e.objectGuid, "UQ__ContactS__3E543F9499F07836").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.adminNotes).HasMaxLength(500);
            entity.Property(e => e.email)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.message).IsRequired();
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.subject).HasMaxLength(250);
        });

        modelBuilder.Entity<DocumentDownload>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Document__3213E83F72125143");

            entity.ToTable("DocumentDownload", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_DocumentDownload_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_DocumentDownload_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_DocumentDownload_tenantGuid_deleted");

            entity.HasIndex(e => e.objectGuid, "UQ__Document__3E543F9439540086").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.categoryName).HasMaxLength(100);
            entity.Property(e => e.fileName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.filePath)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.isPublished).HasDefaultValue(true);
            entity.Property(e => e.mimeType).HasMaxLength(100);
            entity.Property(e => e.title)
                .IsRequired()
                .HasMaxLength(250);
        });

        modelBuilder.Entity<GalleryAlbum>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__GalleryA__3213E83FB1BF2BEC");

            entity.ToTable("GalleryAlbum", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_GalleryAlbum_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_GalleryAlbum_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_GalleryAlbum_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.slug }, "I_GalleryAlbum_tenantGuid_slug").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__GalleryA__3E543F94024167AF").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.coverImageUrl).HasMaxLength(500);
            entity.Property(e => e.isPublished).HasDefaultValue(true);
            entity.Property(e => e.slug)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.title)
                .IsRequired()
                .HasMaxLength(250);
        });

        modelBuilder.Entity<GalleryImage>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__GalleryI__3213E83F49C168A7");

            entity.ToTable("GalleryImage", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_GalleryImage_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_GalleryImage_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_GalleryImage_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.galleryAlbumId }, "I_GalleryImage_tenantGuid_galleryAlbumId");

            entity.HasIndex(e => e.objectGuid, "UQ__GalleryI__3E543F94BF936377").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.altText).HasMaxLength(250);
            entity.Property(e => e.caption).HasMaxLength(500);
            entity.Property(e => e.imageUrl)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.galleryAlbum).WithMany(p => p.GalleryImages)
                .HasForeignKey(d => d.galleryAlbumId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<MediaAsset>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__MediaAss__3213E83FBDFB2887");

            entity.ToTable("MediaAsset", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_MediaAsset_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_MediaAsset_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_MediaAsset_tenantGuid_deleted");

            entity.HasIndex(e => e.objectGuid, "UQ__MediaAss__3E543F940D131572").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.altText).HasMaxLength(250);
            entity.Property(e => e.caption).HasMaxLength(500);
            entity.Property(e => e.fileName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.filePath)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.mimeType)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Menu>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Menu__3213E83FB10FD218");

            entity.ToTable("Menu", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_Menu_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_Menu_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_Menu_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "I_Menu_tenantGuid_name");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "UC_Menu_tenantGuid_name").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__Menu__3E543F94ED37095B").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.location)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<MenuItem>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__MenuItem__3213E83F7E2371E4");

            entity.ToTable("MenuItem", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_MenuItem_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_MenuItem_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_MenuItem_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.menuId }, "I_MenuItem_tenantGuid_menuId");

            entity.HasIndex(e => new { e.tenantGuid, e.pageId }, "I_MenuItem_tenantGuid_pageId");

            entity.HasIndex(e => new { e.tenantGuid, e.parentMenuItemId }, "I_MenuItem_tenantGuid_parentMenuItemId");

            entity.HasIndex(e => e.objectGuid, "UQ__MenuItem__3E543F9445F6D3A0").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.iconClass).HasMaxLength(50);
            entity.Property(e => e.label)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.url).HasMaxLength(500);

            entity.HasOne(d => d.menu).WithMany(p => p.MenuItems)
                .HasForeignKey(d => d.menuId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.page).WithMany(p => p.MenuItems).HasForeignKey(d => d.pageId);

            entity.HasOne(d => d.parentMenuItem).WithMany(p => p.InverseparentMenuItem).HasForeignKey(d => d.parentMenuItemId);
        });

        modelBuilder.Entity<Page>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Page__3213E83F6FDC736F");

            entity.ToTable("Page", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_Page_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_Page_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_Page_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.slug }, "I_Page_tenantGuid_slug").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__Page__3E543F94059B313E").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.featuredImageUrl).HasMaxLength(500);
            entity.Property(e => e.metaDescription).HasMaxLength(500);
            entity.Property(e => e.slug)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.sortOrder).HasDefaultValue(0);
            entity.Property(e => e.title)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);
        });

        modelBuilder.Entity<PageChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__PageChan__3213E83FB3C7B03E");

            entity.ToTable("PageChangeHistory", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_PageChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.pageId }, "I_PageChangeHistory_tenantGuid_pageId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_PageChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_PageChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_PageChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.page).WithMany(p => p.PageChangeHistories)
                .HasForeignKey(d => d.pageId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Post__3213E83FADFE0BF7");

            entity.ToTable("Post", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_Post_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_Post_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_Post_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.postCategoryId }, "I_Post_tenantGuid_postCategoryId");

            entity.HasIndex(e => new { e.tenantGuid, e.slug }, "I_Post_tenantGuid_slug").IsUnique();

            entity.HasIndex(e => new { e.tenantGuid, e.title }, "I_Post_tenantGuid_title");

            entity.HasIndex(e => e.objectGuid, "UQ__Post__3E543F943F9838DE").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.authorName).HasMaxLength(100);
            entity.Property(e => e.excerpt).HasMaxLength(500);
            entity.Property(e => e.featuredImageUrl).HasMaxLength(500);
            entity.Property(e => e.metaDescription).HasMaxLength(500);
            entity.Property(e => e.slug)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.title)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.versionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.postCategory).WithMany(p => p.Posts).HasForeignKey(d => d.postCategoryId);
        });

        modelBuilder.Entity<PostCategory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__PostCate__3213E83FBB22EBB6");

            entity.ToTable("PostCategory", "Community");

            entity.HasIndex(e => e.active, "I_PostCategory_active");

            entity.HasIndex(e => e.deleted, "I_PostCategory_deleted");

            entity.HasIndex(e => e.name, "I_PostCategory_name");

            entity.HasIndex(e => e.slug, "I_PostCategory_slug").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__PostCate__3E543F9471D8369E").IsUnique();

            entity.HasIndex(e => e.name, "UQ__PostCate__72E12F1B512D56D5").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.slug)
                .IsRequired()
                .HasMaxLength(250);
        });

        modelBuilder.Entity<PostChangeHistory>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__PostChan__3213E83F81336CE9");

            entity.ToTable("PostChangeHistory", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_PostChangeHistory_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.postId }, "I_PostChangeHistory_tenantGuid_postId");

            entity.HasIndex(e => new { e.tenantGuid, e.timeStamp }, "I_PostChangeHistory_tenantGuid_timeStamp");

            entity.HasIndex(e => new { e.tenantGuid, e.userId }, "I_PostChangeHistory_tenantGuid_userId");

            entity.HasIndex(e => new { e.tenantGuid, e.versionNumber }, "I_PostChangeHistory_tenantGuid_versionNumber");

            entity.Property(e => e.data).IsRequired();

            entity.HasOne(d => d.post).WithMany(p => p.PostChangeHistories)
                .HasForeignKey(d => d.postId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<PostTag>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__PostTag__3213E83F8CDDC9C1");

            entity.ToTable("PostTag", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_PostTag_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_PostTag_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_PostTag_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "I_PostTag_tenantGuid_name");

            entity.HasIndex(e => new { e.tenantGuid, e.slug }, "I_PostTag_tenantGuid_slug").IsUnique();

            entity.HasIndex(e => new { e.tenantGuid, e.name }, "UC_PostTag_tenantGuid_name").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__PostTag__3E543F94B38B708E").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.slug)
                .IsRequired()
                .HasMaxLength(250);
        });

        modelBuilder.Entity<PostTagAssignment>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__PostTagA__3213E83F46294E37");

            entity.ToTable("PostTagAssignment", "Community");

            entity.HasIndex(e => e.active, "I_PostTagAssignment_active");

            entity.HasIndex(e => e.deleted, "I_PostTagAssignment_deleted");

            entity.HasIndex(e => e.postId, "I_PostTagAssignment_postId");

            entity.HasIndex(e => e.postTagId, "I_PostTagAssignment_postTagId");

            entity.HasIndex(e => new { e.postId, e.postTagId }, "UC_PostTagAssignment_postId_postTagId").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__PostTagA__3E543F94758E3A7A").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);

            entity.HasOne(d => d.post).WithMany(p => p.PostTagAssignments)
                .HasForeignKey(d => d.postId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.postTag).WithMany(p => p.PostTagAssignments)
                .HasForeignKey(d => d.postTagId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<SiteSetting>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__SiteSett__3213E83F7B57ABDB");

            entity.ToTable("SiteSetting", "Community");

            entity.HasIndex(e => e.tenantGuid, "I_SiteSetting_tenantGuid");

            entity.HasIndex(e => new { e.tenantGuid, e.active }, "I_SiteSetting_tenantGuid_active");

            entity.HasIndex(e => new { e.tenantGuid, e.deleted }, "I_SiteSetting_tenantGuid_deleted");

            entity.HasIndex(e => new { e.tenantGuid, e.settingKey }, "I_SiteSetting_tenantGuid_settingKey").IsUnique();

            entity.HasIndex(e => e.objectGuid, "UQ__SiteSett__3E543F9414C20164").IsUnique();

            entity.Property(e => e.active).HasDefaultValue(true);
            entity.Property(e => e.description).HasMaxLength(250);
            entity.Property(e => e.settingGroup).HasMaxLength(50);
            entity.Property(e => e.settingKey)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}