// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Community.Database;

public partial class ContactSubmission
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string name { get; set; }

    public string email { get; set; }

    public string subject { get; set; }

    public string message { get; set; }

    public DateTime submittedDate { get; set; }

    public bool isRead { get; set; }

    public bool isArchived { get; set; }

    public string adminNotes { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }
}