// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Community.Database;

public partial class GalleryImage
{
    public int Id { get; set; }

    public int GalleryAlbumId { get; set; }

    public string ImageUrl { get; set; }

    public string Caption { get; set; }

    public string AltText { get; set; }

    public int? Sequence { get; set; }

    public Guid ObjectGuid { get; set; }

    public bool Active { get; set; }

    public bool Deleted { get; set; }

    public virtual GalleryAlbum GalleryAlbum { get; set; }
}