// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Community.Database;

public partial class MediaAsset
{
    public int Id { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public string MimeType { get; set; }

    public string AltText { get; set; }

    public string Caption { get; set; }

    public long? FileSizeBytes { get; set; }

    public int? ImageWidth { get; set; }

    public int? ImageHeight { get; set; }

    public Guid ObjectGuid { get; set; }

    public bool Active { get; set; }

    public bool Deleted { get; set; }
}