// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Community.Database;

public partial class PostChangeHistory
{
    public int Id { get; set; }

    public int PostId { get; set; }

    public int VersionNumber { get; set; }

    public DateTime TimeStamp { get; set; }

    public int UserId { get; set; }

    public string Data { get; set; }

    public virtual Post Post { get; set; }
}