// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Community.Database;

public partial class Post
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Slug { get; set; }

    public string Body { get; set; }

    public string Excerpt { get; set; }

    public string AuthorName { get; set; }

    public int? PostCategoryId { get; set; }

    public string FeaturedImageUrl { get; set; }

    public string MetaDescription { get; set; }

    public bool IsPublished { get; set; }

    public DateTime? PublishedDate { get; set; }

    public bool IsFeatured { get; set; }

    public int VersionNumber { get; set; }

    public Guid ObjectGuid { get; set; }

    public bool Active { get; set; }

    public bool Deleted { get; set; }

    public virtual PostCategory PostCategory { get; set; }

    public virtual ICollection<PostChangeHistory> PostChangeHistories { get; set; } = new List<PostChangeHistory>();

    public virtual ICollection<PostTagAssignment> PostTagAssignments { get; set; } = new List<PostTagAssignment>();
}