// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Community.Database;

public partial class SiteSetting
{
    public int Id { get; set; }

    public string SettingKey { get; set; }

    public string SettingValue { get; set; }

    public string Description { get; set; }

    public string SettingGroup { get; set; }

    public Guid ObjectGuid { get; set; }

    public bool Active { get; set; }

    public bool Deleted { get; set; }
}