// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class Appeal
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int? campaignId { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public decimal? costPerUnit { get; set; }

    public string notes { get; set; }

    public int? iconId { get; set; }

    public string color { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<AppealChangeHistory> AppealChangeHistories { get; set; } = new List<AppealChangeHistory>();

    public virtual ICollection<Batch> Batches { get; set; } = new List<Batch>();

    public virtual ICollection<Gift> Gifts { get; set; } = new List<Gift>();

    public virtual ICollection<Pledge> Pledges { get; set; } = new List<Pledge>();

    public virtual Campaign campaign { get; set; }

    public virtual Icon icon { get; set; }
}