// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class AssignmentRole
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public int? iconId { get; set; }

    public string color { get; set; }

    public int? sequence { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<AssignmentRoleQualificationRequirement> AssignmentRoleQualificationRequirements { get; set; } = new List<AssignmentRoleQualificationRequirement>();

    public virtual ICollection<CrewMember> CrewMembers { get; set; } = new List<CrewMember>();

    public virtual ICollection<EventResourceAssignment> EventResourceAssignments { get; set; } = new List<EventResourceAssignment>();

    public virtual ICollection<RateSheet> RateSheets { get; set; } = new List<RateSheet>();

    public virtual Icon icon { get; set; }
}