// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class AttributeDefinition
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int? attributeDefinitionEntityId { get; set; }

    public string key { get; set; }

    public string label { get; set; }

    public int? attributeDefinitionTypeId { get; set; }

    public string options { get; set; }

    public bool isRequired { get; set; }

    public int? sequence { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<AttributeDefinitionChangeHistory> AttributeDefinitionChangeHistories { get; set; } = new List<AttributeDefinitionChangeHistory>();

    public virtual AttributeDefinitionEntity attributeDefinitionEntity { get; set; }

    public virtual AttributeDefinitionType attributeDefinitionType { get; set; }
}