// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class Batch
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string batchNumber { get; set; }

    public string description { get; set; }

    public DateTime dateOpened { get; set; }

    public DateTime? datePosted { get; set; }

    public int batchStatusId { get; set; }

    public decimal controlAmount { get; set; }

    public int controlCount { get; set; }

    public int? defaultFundId { get; set; }

    public int? defaultCampaignId { get; set; }

    public int? defaultAppealId { get; set; }

    public DateOnly? defaultDate { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<BatchChangeHistory> BatchChangeHistories { get; set; } = new List<BatchChangeHistory>();

    public virtual ICollection<Gift> Gifts { get; set; } = new List<Gift>();

    public virtual BatchStatus batchStatus { get; set; }

    public virtual Appeal defaultAppeal { get; set; }

    public virtual Campaign defaultCampaign { get; set; }

    public virtual Fund defaultFund { get; set; }
}