// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class Budget
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int financialCategoryId { get; set; }

    public int fiscalPeriodId { get; set; }

    public int? financialOfficeId { get; set; }

    public decimal budgetedAmount { get; set; }

    public decimal? revisedAmount { get; set; }

    public string notes { get; set; }

    public int currencyId { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<BudgetChangeHistory> BudgetChangeHistories { get; set; } = new List<BudgetChangeHistory>();

    public virtual Currency currency { get; set; }

    public virtual FinancialCategory financialCategory { get; set; }

    public virtual FinancialOffice financialOffice { get; set; }

    public virtual FiscalPeriod fiscalPeriod { get; set; }
}