// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class Calendar
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public int? officeId { get; set; }

    public bool? isDefault { get; set; }

    public int? iconId { get; set; }

    public string color { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public int versionNumber { get; set; }

    public virtual ICollection<CalendarChangeHistory> CalendarChangeHistories { get; set; } = new List<CalendarChangeHistory>();

    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();

    public virtual ICollection<EventCalendar> EventCalendars { get; set; } = new List<EventCalendar>();

    public virtual ICollection<SchedulingTarget> SchedulingTargets { get; set; } = new List<SchedulingTarget>();

    public virtual Icon icon { get; set; }

    public virtual Office office { get; set; }
}