// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class CallEventLog
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int callId { get; set; }

    public string eventType { get; set; }

    public int? userId { get; set; }

    public string providerId { get; set; }

    public string metadata { get; set; }

    public DateTime dateTimeCreated { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual Call call { get; set; }
}