// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class Contact
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int contactTypeId { get; set; }

    public string firstName { get; set; }

    public string middleName { get; set; }

    public string lastName { get; set; }

    public int? salutationId { get; set; }

    public string title { get; set; }

    public DateOnly? birthDate { get; set; }

    public string company { get; set; }

    public string email { get; set; }

    public string phone { get; set; }

    public string mobile { get; set; }

    public string position { get; set; }

    public string webSite { get; set; }

    public int? contactMethodId { get; set; }

    public string notes { get; set; }

    public int? timeZoneId { get; set; }

    public string attributes { get; set; }

    public int? iconId { get; set; }

    public string color { get; set; }

    public string avatarFileName { get; set; }

    public long? avatarSize { get; set; }

    public byte[] avatarData { get; set; }

    public string avatarMimeType { get; set; }

    public string externalId { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<ClientContact> ClientContacts { get; set; } = new List<ClientContact>();

    public virtual ICollection<Constituent> Constituents { get; set; } = new List<Constituent>();

    public virtual ICollection<ContactChangeHistory> ContactChangeHistories { get; set; } = new List<ContactChangeHistory>();

    public virtual ICollection<ContactContact> ContactContactcontacts { get; set; } = new List<ContactContact>();

    public virtual ICollection<ContactContact> ContactContactrelatedContacts { get; set; } = new List<ContactContact>();

    public virtual ICollection<ContactInteraction> ContactInteractioncontacts { get; set; } = new List<ContactInteraction>();

    public virtual ICollection<ContactInteraction> ContactInteractioninitiatingContacts { get; set; } = new List<ContactInteraction>();

    public virtual ICollection<ContactTag> ContactTags { get; set; } = new List<ContactTag>();

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual ICollection<EventNotificationSubscription> EventNotificationSubscriptions { get; set; } = new List<EventNotificationSubscription>();

    public virtual ICollection<EventResourceAssignment> EventResourceAssignments { get; set; } = new List<EventResourceAssignment>();

    public virtual ICollection<FinancialTransaction> FinancialTransactions { get; set; } = new List<FinancialTransaction>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<OfficeContact> OfficeContacts { get; set; } = new List<OfficeContact>();

    public virtual ICollection<Receipt> Receipts { get; set; } = new List<Receipt>();

    public virtual ICollection<ResourceContact> ResourceContacts { get; set; } = new List<ResourceContact>();

    public virtual ICollection<SchedulingTargetContact> SchedulingTargetContacts { get; set; } = new List<SchedulingTargetContact>();

    public virtual ContactMethod contactMethod { get; set; }

    public virtual ContactType contactType { get; set; }

    public virtual Icon icon { get; set; }

    public virtual Salutation salutation { get; set; }

    public virtual TimeZone timeZone { get; set; }
}