// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class ContactInteraction
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int contactId { get; set; }

    public int? initiatingContactId { get; set; }

    public int interactionTypeId { get; set; }

    public int? scheduledEventId { get; set; }

    public DateTime startTime { get; set; }

    public DateTime? endTime { get; set; }

    public string notes { get; set; }

    public string location { get; set; }

    public int? priorityId { get; set; }

    public string externalId { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<ContactInteractionChangeHistory> ContactInteractionChangeHistories { get; set; } = new List<ContactInteractionChangeHistory>();

    public virtual Contact contact { get; set; }

    public virtual Contact initiatingContact { get; set; }

    public virtual InteractionType interactionType { get; set; }

    public virtual Priority priority { get; set; }

    public virtual ScheduledEvent scheduledEvent { get; set; }
}