// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class CrewMember
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int crewId { get; set; }

    public int resourceId { get; set; }

    public int? assignmentRoleId { get; set; }

    public int sequence { get; set; }

    public int? iconId { get; set; }

    public string color { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<CrewMemberChangeHistory> CrewMemberChangeHistories { get; set; } = new List<CrewMemberChangeHistory>();

    public virtual AssignmentRole assignmentRole { get; set; }

    public virtual Crew crew { get; set; }

    public virtual Icon icon { get; set; }

    public virtual Resource resource { get; set; }
}