// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class DocumentFolder
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public int? parentDocumentFolderId { get; set; }

    public int? iconId { get; set; }

    public string color { get; set; }

    public int sequence { get; set; }

    public string notes { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<DocumentFolderChangeHistory> DocumentFolderChangeHistories { get; set; } = new List<DocumentFolderChangeHistory>();

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual ICollection<DocumentFolder> InverseparentDocumentFolder { get; set; } = new List<DocumentFolder>();

    public virtual Icon icon { get; set; }

    public virtual DocumentFolder parentDocumentFolder { get; set; }
}