// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class DocumentDocumentTag
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public int documentId { get; set; }

    public int documentTagId { get; set; }

    public virtual ICollection<DocumentDocumentTagChangeHistory> DocumentDocumentTagChangeHistories { get; set; } = new List<DocumentDocumentTagChangeHistory>();

    public virtual Document document { get; set; }

    public virtual DocumentTag documentTag { get; set; }
}