// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class EventCalendar
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int scheduledEventId { get; set; }

    public int calendarId { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual Calendar calendar { get; set; }

    public virtual ScheduledEvent scheduledEvent { get; set; }
}