// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class EventNotificationSubscription
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int? resourceId { get; set; }

    public int? contactId { get; set; }

    public int eventNotificationTypeId { get; set; }

    public int triggerEvents { get; set; }

    public string recipientAddress { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<EventNotificationSubscriptionChangeHistory> EventNotificationSubscriptionChangeHistories { get; set; } = new List<EventNotificationSubscriptionChangeHistory>();

    public virtual Contact contact { get; set; }

    public virtual EventNotificationType eventNotificationType { get; set; }

    public virtual Resource resource { get; set; }
}