// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class EventType
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string color { get; set; }

    public int? iconId { get; set; }

    public int? sequence { get; set; }

    public bool requiresRentalAgreement { get; set; }

    public bool requiresExternalContact { get; set; }

    public bool requiresPayment { get; set; }

    public bool requiresDeposit { get; set; }

    public bool requiresBarService { get; set; }

    public bool allowsTicketSales { get; set; }

    public bool isInternalEvent { get; set; }

    public decimal? defaultPrice { get; set; }

    public int? chargeTypeId { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<EventTypeChangeHistory> EventTypeChangeHistories { get; set; } = new List<EventTypeChangeHistory>();

    public virtual ICollection<ScheduledEvent> ScheduledEvents { get; set; } = new List<ScheduledEvent>();

    public virtual ChargeType chargeType { get; set; }

    public virtual Icon icon { get; set; }
}