// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class EventCharge
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int scheduledEventId { get; set; }

    public int? resourceId { get; set; }

    public int chargeTypeId { get; set; }

    public int chargeStatusId { get; set; }

    public decimal? quantity { get; set; }

    public decimal? unitPrice { get; set; }

    public decimal extendedAmount { get; set; }

    public decimal taxAmount { get; set; }

    public decimal totalAmount { get; set; }

    public string description { get; set; }

    public int currencyId { get; set; }

    public int? rateTypeId { get; set; }

    public string notes { get; set; }

    public bool isAutomatic { get; set; }

    public bool isDeposit { get; set; }

    public DateTime? depositRefundedDate { get; set; }

    public DateTime? exportedDate { get; set; }

    public string externalId { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public int? taxCodeId { get; set; }

    public virtual ICollection<EventChargeChangeHistory> EventChargeChangeHistories { get; set; } = new List<EventChargeChangeHistory>();

    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; } = new List<PaymentTransaction>();

    public virtual ChargeStatus chargeStatus { get; set; }

    public virtual ChargeType chargeType { get; set; }

    public virtual Currency currency { get; set; }

    public virtual RateType rateType { get; set; }

    public virtual Resource resource { get; set; }

    public virtual ScheduledEvent scheduledEvent { get; set; }

    public virtual TaxCode taxCode { get; set; }
}