// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class EventResourceAssignment
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int scheduledEventId { get; set; }

    public int? officeId { get; set; }

    public int? resourceId { get; set; }

    public int? crewId { get; set; }

    public int? volunteerGroupId { get; set; }

    public int? assignmentRoleId { get; set; }

    public int assignmentStatusId { get; set; }

    public DateTime? assignmentStartDateTime { get; set; }

    public DateTime? assignmentEndDateTime { get; set; }

    public string notes { get; set; }

    public bool? isTravelRequired { get; set; }

    public int? travelDurationMinutes { get; set; }

    public float? distanceKilometers { get; set; }

    public string startLocation { get; set; }

    public DateTime? actualStartDateTime { get; set; }

    public DateTime? actualEndDateTime { get; set; }

    public string actualNotes { get; set; }

    public bool isVolunteer { get; set; }

    public float? reportedVolunteerHours { get; set; }

    public float? approvedVolunteerHours { get; set; }

    public int? hoursApprovedByContactId { get; set; }

    public DateTime? approvedDateTime { get; set; }

    public decimal? reimbursementAmount { get; set; }

    public int? chargeTypeId { get; set; }

    public bool reimbursementRequested { get; set; }

    public string volunteerNotes { get; set; }

    public DateTime? reminderSentDateTime { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<EventResourceAssignmentChangeHistory> EventResourceAssignmentChangeHistories { get; set; } = new List<EventResourceAssignmentChangeHistory>();

    public virtual AssignmentRole assignmentRole { get; set; }

    public virtual AssignmentStatus assignmentStatus { get; set; }

    public virtual ChargeType chargeType { get; set; }

    public virtual Crew crew { get; set; }

    public virtual Contact hoursApprovedByContact { get; set; }

    public virtual Office office { get; set; }

    public virtual Resource resource { get; set; }

    public virtual ScheduledEvent scheduledEvent { get; set; }

    public virtual VolunteerGroup volunteerGroup { get; set; }
}