// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class FinancialOffice
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string code { get; set; }

    public string contactName { get; set; }

    public string contactEmail { get; set; }

    public string exportFormat { get; set; }

    public string color { get; set; }

    public int? sequence { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<Budget> Budgets { get; set; } = new List<Budget>();

    public virtual ICollection<FinancialCategory> FinancialCategories { get; set; } = new List<FinancialCategory>();

    public virtual ICollection<FinancialOfficeChangeHistory> FinancialOfficeChangeHistories { get; set; } = new List<FinancialOfficeChangeHistory>();

    public virtual ICollection<FinancialTransaction> FinancialTransactions { get; set; } = new List<FinancialTransaction>();
}