// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class FinancialCategory
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string code { get; set; }

    public int accountTypeId { get; set; }

    public int? parentFinancialCategoryId { get; set; }

    public bool isTaxApplicable { get; set; }

    public decimal? defaultAmount { get; set; }

    public string externalAccountId { get; set; }

    public int? sequence { get; set; }

    public string color { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<Budget> Budgets { get; set; } = new List<Budget>();

    public virtual ICollection<ChargeType> ChargeTypes { get; set; } = new List<ChargeType>();

    public virtual ICollection<FinancialCategoryChangeHistory> FinancialCategoryChangeHistories { get; set; } = new List<FinancialCategoryChangeHistory>();

    public virtual ICollection<FinancialTransaction> FinancialTransactions { get; set; } = new List<FinancialTransaction>();

    public virtual ICollection<FinancialCategory> InverseparentFinancialCategory { get; set; } = new List<FinancialCategory>();

    public virtual AccountType accountType { get; set; }

    public virtual FinancialCategory parentFinancialCategory { get; set; }
}