// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class FiscalPeriod
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public DateTime startDate { get; set; }

    public DateTime endDate { get; set; }

    public string periodType { get; set; }

    public int fiscalYear { get; set; }

    public int periodNumber { get; set; }

    public bool isClosed { get; set; }

    public DateTime? closedDate { get; set; }

    public string closedBy { get; set; }

    public int? sequence { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<FinancialTransaction> FinancialTransactions { get; set; } = new List<FinancialTransaction>();

    public virtual ICollection<FiscalPeriodChangeHistory> FiscalPeriodChangeHistories { get; set; } = new List<FiscalPeriodChangeHistory>();
}