// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class GeneralLedgerEntry
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int journalEntryNumber { get; set; }

    public DateTime transactionDate { get; set; }

    public string description { get; set; }

    public string referenceNumber { get; set; }

    public int? financialTransactionId { get; set; }

    public int? fiscalPeriodId { get; set; }

    public int? financialOfficeId { get; set; }

    public int postedBy { get; set; }

    public DateTime postedDate { get; set; }

    public int? reversalOfId { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<GeneralLedgerLine> GeneralLedgerLines { get; set; } = new List<GeneralLedgerLine>();

    public virtual FinancialOffice financialOffice { get; set; }

    public virtual FinancialTransaction financialTransaction { get; set; }

    public virtual FiscalPeriod fiscalPeriod { get; set; }
}