// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class Gift
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int? officeId { get; set; }

    public int constituentId { get; set; }

    public int? pledgeId { get; set; }

    public decimal amount { get; set; }

    public DateTime receivedDate { get; set; }

    public DateTime? postedDate { get; set; }

    public int fundId { get; set; }

    public int? campaignId { get; set; }

    public int? appealId { get; set; }

    public int paymentTypeId { get; set; }

    public string referenceNumber { get; set; }

    public int? batchId { get; set; }

    public int? receiptTypeId { get; set; }

    public DateTime? receiptDate { get; set; }

    public int? tributeId { get; set; }

    public string notes { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<GiftChangeHistory> GiftChangeHistories { get; set; } = new List<GiftChangeHistory>();

    public virtual ICollection<SoftCredit> SoftCredits { get; set; } = new List<SoftCredit>();

    public virtual Appeal appeal { get; set; }

    public virtual Batch batch { get; set; }

    public virtual Campaign campaign { get; set; }

    public virtual Constituent constituent { get; set; }

    public virtual Fund fund { get; set; }

    public virtual Office office { get; set; }

    public virtual PaymentType paymentType { get; set; }

    public virtual Pledge pledge { get; set; }

    public virtual ReceiptType receiptType { get; set; }

    public virtual Tribute tribute { get; set; }
}