// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class NotificationSubscription
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int? resourceId { get; set; }

    public int? contactId { get; set; }

    public int notificationTypeId { get; set; }

    public int triggerEvents { get; set; }

    public string recipientAddress { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<NotificationSubscriptionChangeHistory> NotificationSubscriptionChangeHistories { get; set; } = new List<NotificationSubscriptionChangeHistory>();

    public virtual Contact contact { get; set; }

    public virtual NotificationType notificationType { get; set; }

    public virtual Resource resource { get; set; }
}