// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class NotificationDistribution
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int notificationId { get; set; }

    public int userId { get; set; }

    public bool acknowledged { get; set; }

    public DateTime? dateTimeAcknowledged { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual Notification notification { get; set; }
}