// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class Office
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public int officeTypeId { get; set; }

    public int timeZoneId { get; set; }

    public int currencyId { get; set; }

    public string addressLine1 { get; set; }

    public string addressLine2 { get; set; }

    public string city { get; set; }

    public string postalCode { get; set; }

    public int stateProvinceId { get; set; }

    public int countryId { get; set; }

    public string phone { get; set; }

    public string email { get; set; }

    public double? latitude { get; set; }

    public double? longitude { get; set; }

    public string notes { get; set; }

    public string externalId { get; set; }

    public string color { get; set; }

    public string attributes { get; set; }

    public string avatarFileName { get; set; }

    public long? avatarSize { get; set; }

    public byte[] avatarData { get; set; }

    public string avatarMimeType { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<Calendar> Calendars { get; set; } = new List<Calendar>();

    public virtual ICollection<Crew> Crews { get; set; } = new List<Crew>();

    public virtual ICollection<EventResourceAssignment> EventResourceAssignments { get; set; } = new List<EventResourceAssignment>();

    public virtual ICollection<Gift> Gifts { get; set; } = new List<Gift>();

    public virtual ICollection<OfficeChangeHistory> OfficeChangeHistories { get; set; } = new List<OfficeChangeHistory>();

    public virtual ICollection<OfficeContact> OfficeContacts { get; set; } = new List<OfficeContact>();

    public virtual ICollection<RateSheet> RateSheets { get; set; } = new List<RateSheet>();

    public virtual ICollection<Resource> Resources { get; set; } = new List<Resource>();

    public virtual ICollection<ScheduledEvent> ScheduledEvents { get; set; } = new List<ScheduledEvent>();

    public virtual ICollection<SchedulingTarget> SchedulingTargets { get; set; } = new List<SchedulingTarget>();

    public virtual ICollection<VolunteerGroup> VolunteerGroups { get; set; } = new List<VolunteerGroup>();

    public virtual Country country { get; set; }

    public virtual Currency currency { get; set; }

    public virtual OfficeType officeType { get; set; }

    public virtual StateProvince stateProvince { get; set; }

    public virtual TimeZone timeZone { get; set; }
}