// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class PaymentTransaction
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int paymentMethodId { get; set; }

    public int? paymentProviderId { get; set; }

    public int? scheduledEventId { get; set; }

    public int? financialTransactionId { get; set; }

    public int? eventChargeId { get; set; }

    public DateTime transactionDate { get; set; }

    public decimal amount { get; set; }

    public decimal processingFee { get; set; }

    public decimal netAmount { get; set; }

    public int currencyId { get; set; }

    public string status { get; set; }

    public string providerTransactionId { get; set; }

    public string providerResponse { get; set; }

    public string payerName { get; set; }

    public string payerEmail { get; set; }

    public string payerPhone { get; set; }

    public string receiptNumber { get; set; }

    public string notes { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual ICollection<PaymentTransactionChangeHistory> PaymentTransactionChangeHistories { get; set; } = new List<PaymentTransactionChangeHistory>();

    public virtual ICollection<Receipt> Receipts { get; set; } = new List<Receipt>();

    public virtual Currency currency { get; set; }

    public virtual EventCharge eventCharge { get; set; }

    public virtual FinancialTransaction financialTransaction { get; set; }

    public virtual PaymentMethod paymentMethod { get; set; }

    public virtual PaymentProvider paymentProvider { get; set; }

    public virtual ScheduledEvent scheduledEvent { get; set; }
}