// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class PaymentProvider
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string providerType { get; set; }

    public bool isActive { get; set; }

    public string apiKeyEncrypted { get; set; }

    public string merchantId { get; set; }

    public string webhookSecret { get; set; }

    public decimal? processingFeePercent { get; set; }

    public decimal? processingFeeFixed { get; set; }

    public string notes { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<PaymentProviderChangeHistory> PaymentProviderChangeHistories { get; set; } = new List<PaymentProviderChangeHistory>();

    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; } = new List<PaymentTransaction>();
}