// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class PushProviderConfiguration
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string providerId { get; set; }

    public bool enabled { get; set; }

    public string configurationJson { get; set; }

    public DateTime dateTimeModified { get; set; }

    public int modifiedByUserId { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }
}