// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class RateSheet
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int? officeId { get; set; }

    public int? assignmentRoleId { get; set; }

    public int? resourceId { get; set; }

    public int? schedulingTargetId { get; set; }

    public int rateTypeId { get; set; }

    public DateTime effectiveDate { get; set; }

    public int currencyId { get; set; }

    public decimal costRate { get; set; }

    public decimal billingRate { get; set; }

    public string notes { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<RateSheetChangeHistory> RateSheetChangeHistories { get; set; } = new List<RateSheetChangeHistory>();

    public virtual AssignmentRole assignmentRole { get; set; }

    public virtual Currency currency { get; set; }

    public virtual Office office { get; set; }

    public virtual RateType rateType { get; set; }

    public virtual Resource resource { get; set; }

    public virtual SchedulingTarget schedulingTarget { get; set; }
}