// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class RelationshipType
{
    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public bool isEmergencyEligible { get; set; }

    public int? sequence { get; set; }

    public int? iconId { get; set; }

    public string color { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<ClientContact> ClientContacts { get; set; } = new List<ClientContact>();

    public virtual ICollection<ContactContact> ContactContacts { get; set; } = new List<ContactContact>();

    public virtual ICollection<OfficeContact> OfficeContacts { get; set; } = new List<OfficeContact>();

    public virtual ICollection<ResourceContact> ResourceContacts { get; set; } = new List<ResourceContact>();

    public virtual ICollection<SchedulingTargetContact> SchedulingTargetContacts { get; set; } = new List<SchedulingTargetContact>();

    public virtual Icon icon { get; set; }
}