// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class ResourceShift
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int resourceId { get; set; }

    public int dayOfWeek { get; set; }

    public int? timeZoneId { get; set; }

    public TimeOnly startTime { get; set; }

    public float hours { get; set; }

    public string label { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<ResourceShiftChangeHistory> ResourceShiftChangeHistories { get; set; } = new List<ResourceShiftChangeHistory>();

    public virtual Resource resource { get; set; }

    public virtual TimeZone timeZone { get; set; }
}