// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class ResourceContact
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int resourceId { get; set; }

    public int contactId { get; set; }

    public bool isPrimary { get; set; }

    public int relationshipTypeId { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<ResourceContactChangeHistory> ResourceContactChangeHistories { get; set; } = new List<ResourceContactChangeHistory>();

    public virtual Contact contact { get; set; }

    public virtual RelationshipType relationshipType { get; set; }

    public virtual Resource resource { get; set; }
}