// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class ResourceAvailability
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int resourceId { get; set; }

    public int? timeZoneId { get; set; }

    public DateTime startDateTime { get; set; }

    public DateTime? endDateTime { get; set; }

    public string reason { get; set; }

    public string notes { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<ResourceAvailabilityChangeHistory> ResourceAvailabilityChangeHistories { get; set; } = new List<ResourceAvailabilityChangeHistory>();

    public virtual Resource resource { get; set; }

    public virtual TimeZone timeZone { get; set; }
}