// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class SalesforceTenantLink
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public bool syncEnabled { get; set; }

    public string syncDirectionFlags { get; set; }

    public int? pullIntervalMinutes { get; set; }

    public DateTime? lastPullDate { get; set; }

    public string loginUrl { get; set; }

    public string sfClientId { get; set; }

    public string sfClientSecret { get; set; }

    public string sfUsername { get; set; }

    public string sfPassword { get; set; }

    public string sfSecurityToken { get; set; }

    public string instanceUrl { get; set; }

    public string apiVersion { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<SalesforceTenantLinkChangeHistory> SalesforceTenantLinkChangeHistories { get; set; } = new List<SalesforceTenantLinkChangeHistory>();
}