// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class SalesforceSyncQueue
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string entityType { get; set; }

    public string operationType { get; set; }

    public int entityId { get; set; }

    public string payload { get; set; }

    public string status { get; set; }

    public int attemptCount { get; set; }

    public int maxAttempts { get; set; }

    public DateTime? lastAttemptDate { get; set; }

    public DateTime? completedDate { get; set; }

    public DateTime? createdDate { get; set; }

    public string errorMessage { get; set; }

    public string responseBody { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }
}