// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class SchedulingTargetType
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public int? sequence { get; set; }

    public int? iconId { get; set; }

    public string color { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<ScheduledEventTemplate> ScheduledEventTemplates { get; set; } = new List<ScheduledEventTemplate>();

    public virtual ICollection<SchedulingTarget> SchedulingTargets { get; set; } = new List<SchedulingTarget>();

    public virtual Icon icon { get; set; }
}