// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class SchedulingTargetAddress
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int schedulingTargetId { get; set; }

    public int? clientId { get; set; }

    public string addressLine1 { get; set; }

    public string addressLine2 { get; set; }

    public string city { get; set; }

    public string postalCode { get; set; }

    public int stateProvinceId { get; set; }

    public int countryId { get; set; }

    public double? latitude { get; set; }

    public double? longitude { get; set; }

    public string label { get; set; }

    public bool isPrimary { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<SchedulingTargetAddressChangeHistory> SchedulingTargetAddressChangeHistories { get; set; } = new List<SchedulingTargetAddressChangeHistory>();

    public virtual Client client { get; set; }

    public virtual Country country { get; set; }

    public virtual SchedulingTarget schedulingTarget { get; set; }

    public virtual StateProvince stateProvince { get; set; }
}