// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class ScheduledEventQualificationRequirement
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int scheduledEventId { get; set; }

    public int qualificationId { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<ScheduledEventQualificationRequirementChangeHistory> ScheduledEventQualificationRequirementChangeHistories { get; set; } = new List<ScheduledEventQualificationRequirementChangeHistory>();

    public virtual Qualification qualification { get; set; }

    public virtual ScheduledEvent scheduledEvent { get; set; }
}