// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class ScheduledEvent
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int? officeId { get; set; }

    public int? clientId { get; set; }

    public int? scheduledEventTemplateId { get; set; }

    public int? recurrenceRuleId { get; set; }

    public int? schedulingTargetId { get; set; }

    public int? timeZoneId { get; set; }

    public int? parentScheduledEventId { get; set; }

    public DateTime? recurrenceInstanceDate { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public bool? isAllDay { get; set; }

    public DateTime startDateTime { get; set; }

    public DateTime endDateTime { get; set; }

    public string location { get; set; }

    public int eventStatusId { get; set; }

    public int? resourceId { get; set; }

    public int? crewId { get; set; }

    public int? priorityId { get; set; }

    public int? bookingSourceTypeId { get; set; }

    public int? partySize { get; set; }

    public string notes { get; set; }

    public string color { get; set; }

    public string externalId { get; set; }

    public string attributes { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<ContactInteraction> ContactInteractions { get; set; } = new List<ContactInteraction>();

    public virtual ICollection<EventCalendar> EventCalendars { get; set; } = new List<EventCalendar>();

    public virtual ICollection<EventCharge> EventCharges { get; set; } = new List<EventCharge>();

    public virtual ICollection<EventResourceAssignment> EventResourceAssignments { get; set; } = new List<EventResourceAssignment>();

    public virtual ICollection<ScheduledEvent> InverseparentScheduledEvent { get; set; } = new List<ScheduledEvent>();

    public virtual ICollection<RecurrenceException> RecurrenceExceptions { get; set; } = new List<RecurrenceException>();

    public virtual ICollection<ScheduledEventChangeHistory> ScheduledEventChangeHistories { get; set; } = new List<ScheduledEventChangeHistory>();

    public virtual ICollection<ScheduledEventDependency> ScheduledEventDependencypredecessorEvents { get; set; } = new List<ScheduledEventDependency>();

    public virtual ICollection<ScheduledEventDependency> ScheduledEventDependencysuccessorEvents { get; set; } = new List<ScheduledEventDependency>();

    public virtual ICollection<ScheduledEventQualificationRequirement> ScheduledEventQualificationRequirements { get; set; } = new List<ScheduledEventQualificationRequirement>();

    public virtual BookingSourceType bookingSourceType { get; set; }

    public virtual Client client { get; set; }

    public virtual Crew crew { get; set; }

    public virtual EventStatus eventStatus { get; set; }

    public virtual Office office { get; set; }

    public virtual ScheduledEvent parentScheduledEvent { get; set; }

    public virtual Priority priority { get; set; }

    public virtual RecurrenceRule recurrenceRule { get; set; }

    public virtual Resource resource { get; set; }

    public virtual ScheduledEventTemplate scheduledEventTemplate { get; set; }

    public virtual SchedulingTarget schedulingTarget { get; set; }

    public virtual TimeZone timeZone { get; set; }
}