// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class SchedulingTargetContact
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int schedulingTargetId { get; set; }

    public int contactId { get; set; }

    public bool isPrimary { get; set; }

    public int relationshipTypeId { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<SchedulingTargetContactChangeHistory> SchedulingTargetContactChangeHistories { get; set; } = new List<SchedulingTargetContactChangeHistory>();

    public virtual Contact contact { get; set; }

    public virtual RelationshipType relationshipType { get; set; }

    public virtual SchedulingTarget schedulingTarget { get; set; }
}