// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class ShiftPatternChangeHistory
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int shiftPatternId { get; set; }

    public int versionNumber { get; set; }

    public DateTime timeStamp { get; set; }

    public int userId { get; set; }

    public string data { get; set; }

    public virtual ShiftPattern shiftPattern { get; set; }
}