// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class SoftCredit
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int giftId { get; set; }

    public int constituentId { get; set; }

    public decimal amount { get; set; }

    public string notes { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<SoftCreditChangeHistory> SoftCreditChangeHistories { get; set; } = new List<SoftCreditChangeHistory>();

    public virtual Constituent constituent { get; set; }

    public virtual Gift gift { get; set; }
}