// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class StateProvince
{
    public int id { get; set; }

    public int countryId { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string abbreviation { get; set; }

    public int? sequence { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();

    public virtual ICollection<Office> Offices { get; set; } = new List<Office>();

    public virtual ICollection<SchedulingTargetAddress> SchedulingTargetAddresses { get; set; } = new List<SchedulingTargetAddress>();

    public virtual ICollection<TenantProfile> TenantProfiles { get; set; } = new List<TenantProfile>();

    public virtual Country country { get; set; }
}