// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class Tribute
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public int? tributeTypeId { get; set; }

    public int? defaultAcknowledgeeId { get; set; }

    public DateOnly? startDate { get; set; }

    public DateOnly? endDate { get; set; }

    public int? iconId { get; set; }

    public string color { get; set; }

    public string avatarFileName { get; set; }

    public long? avatarSize { get; set; }

    public byte[] avatarData { get; set; }

    public string avatarMimeType { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<Gift> Gifts { get; set; } = new List<Gift>();

    public virtual ICollection<TributeChangeHistory> TributeChangeHistories { get; set; } = new List<TributeChangeHistory>();

    public virtual Constituent defaultAcknowledgee { get; set; }

    public virtual Icon icon { get; set; }

    public virtual TributeType tributeType { get; set; }
}