// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class VolunteerProfile
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int resourceId { get; set; }

    public int volunteerStatusId { get; set; }

    public DateOnly? onboardedDate { get; set; }

    public DateOnly? inactiveSince { get; set; }

    public float? totalHoursServed { get; set; }

    public DateOnly? lastActivityDate { get; set; }

    public bool backgroundCheckCompleted { get; set; }

    public DateOnly? backgroundCheckDate { get; set; }

    public DateOnly? backgroundCheckExpiry { get; set; }

    public bool confidentialityAgreementSigned { get; set; }

    public DateOnly? confidentialityAgreementDate { get; set; }

    public string availabilityPreferences { get; set; }

    public string interestsAndSkillsNotes { get; set; }

    public string emergencyContactNotes { get; set; }

    public int? constituentId { get; set; }

    public int? iconId { get; set; }

    public string color { get; set; }

    public string attributes { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<VolunteerProfileChangeHistory> VolunteerProfileChangeHistories { get; set; } = new List<VolunteerProfileChangeHistory>();

    public virtual Constituent constituent { get; set; }

    public virtual Icon icon { get; set; }

    public virtual Resource resource { get; set; }

    public virtual VolunteerStatus volunteerStatus { get; set; }
}