// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Foundation.Scheduler.Database;

public partial class VolunteerGroupMember
{
    public int id { get; set; }

    public Guid tenantGuid { get; set; }

    public int volunteerGroupId { get; set; }

    public int resourceId { get; set; }

    public int? assignmentRoleId { get; set; }

    public int sequence { get; set; }

    public DateOnly? joinedDate { get; set; }

    public DateOnly? leftDate { get; set; }

    public string notes { get; set; }

    public int versionNumber { get; set; }

    public Guid objectGuid { get; set; }

    public bool active { get; set; }

    public bool deleted { get; set; }

    public virtual ICollection<VolunteerGroupMemberChangeHistory> VolunteerGroupMemberChangeHistories { get; set; } = new List<VolunteerGroupMemberChangeHistory>();

    public virtual AssignmentRole assignmentRole { get; set; }

    public virtual Resource resource { get; set; }

    public virtual VolunteerGroup volunteerGroup { get; set; }
}