using System;
using System.IO;
using System.Text;
using System.Linq;

namespace Foundation.CodeGeneration
{
    public static class AngularAutomationUtility
    {
        public static void IntegrateGeneratedCode(string projectRoot, string moduleName, string outputRoot, string angularAppRoot, string angularModuleFile = "app.module.ts", string angularRoutingFile = "app-routing.module.ts")
        {
            Console.WriteLine($"Starting Angular module integration for {moduleName}...");

            string angularRootPath = angularAppRoot;
            if (!Directory.Exists(angularRootPath))
            {
                // Fallback or error if the configured root doesn't exist? 
                // Using the passed root.
                if (string.IsNullOrEmpty(angularRootPath) || !Directory.Exists(angularRootPath))
                {
                    Console.WriteLine($"Error: Angular app root directory not found at: {angularRootPath}");
                    return;
                }
            }

            string targetModuleFile = Path.Combine(angularRootPath, angularModuleFile);
            string targetRoutingFile = Path.Combine(angularRootPath, angularRoutingFile);

            if (!File.Exists(targetModuleFile))
            {
                Console.WriteLine($"Error: Target module file not found: {targetModuleFile}");
                return;
            }

            if (!File.Exists(targetRoutingFile))
            {
                Console.WriteLine($"Error: Target routing file not found: {targetRoutingFile}");
                return;
            }

            //
            // 1. Locate Source Files (Generated Lists)
            //
            string angularOutputFolder = Path.Combine(outputRoot, moduleName, "angular");
            
            // Files generated by the generators
            string dataComponentListFile = Path.Combine(angularOutputFolder, $"{moduleName}.data-component.list.for.app.modules.ts.txt");
            string dataComponentRoutesFile = Path.Combine(angularOutputFolder, $"{moduleName}.data-component.routes.for.app.routing.modules.ts.txt");
            string dataServiceListFile = Path.Combine(angularOutputFolder, $"{moduleName}.data.service.list.for.app.modules.ts.txt");

            //
            // 2. Process app.module.ts
            //
            UpdateModuleFile(targetModuleFile, moduleName, dataComponentListFile, dataServiceListFile);

            //
            // 3. Process app-routing.module.ts
            //
            UpdateRoutingFile(targetRoutingFile, moduleName, dataComponentListFile, dataComponentRoutesFile);

            Console.WriteLine("Angular module integration completed.");
        }

        private static void UpdateModuleFile(string targetFile, string moduleName, string componentListSource, string serviceListSource)
        {
            if (!File.Exists(targetFile)) return;

            string fileContent = File.ReadAllText(targetFile);
            bool modified = false;

            //
            // 1. Component Imports
            //
            if (File.Exists(componentListSource))
            {
                string sourceContent = File.ReadAllText(componentListSource);
                string startMarker = $"// Beginning of imports for {moduleName} Data Components";
                string endMarker = $"// End of imports for {moduleName} Data Components";

                string extraction = GetContentBetweenMarkers(sourceContent, startMarker, endMarker);

                if (!string.IsNullOrEmpty(extraction))
                {
                    if (ReplaceContentBetweenMarkers(ref fileContent, startMarker, endMarker, extraction))
                    {
                        modified = true;
                        Console.WriteLine($"Updated component imports in {Path.GetFileName(targetFile)}");
                    }
                    else
                    {
                        Console.WriteLine($"Warning: Could not find markers '{startMarker}' in {Path.GetFileName(targetFile)}");
                    }
                }

                 //
                 // 2. Component Declarations
                 //
                string declStartMarker = $"// Beginning of declarations for {moduleName} Data Components";
                string declEndMarker = $"// End of declarations for {moduleName} Data Components"; // Assumed pattern
                
                // Note: The generator might not write the end marker for declarations in the same way, but let's assume consistency or check if needed.
                // If the user didn't mention it, we assume consistency.
                
                string declExtraction = GetContentBetweenMarkers(sourceContent, declStartMarker, declEndMarker);
                 if (!string.IsNullOrEmpty(declExtraction))
                {
                    if (ReplaceContentBetweenMarkers(ref fileContent, declStartMarker, declEndMarker, declExtraction))
                    {
                        modified = true;
                         Console.WriteLine($"Updated component declarations in {Path.GetFileName(targetFile)}");
                    }
                     // Not all modules might have declarations marker if not generated yet, so we can be silent or warn.
                }
            }
            else
            {
                Console.WriteLine($"Error: Could not find component source list file '{componentListSource}'");
            }


            //
            // 3. Service Imports & Providers
            //
            if (File.Exists(serviceListSource))
            {
                string sourceContent = File.ReadAllText(serviceListSource);
                
                // Service Imports
                string importStartMarker = $"// Beginning of imports for {moduleName} Data Services";
                string importEndMarker = $"// End of imports for {moduleName} Data Services";
                
                string importExtraction = GetContentBetweenMarkers(sourceContent, importStartMarker, importEndMarker);
                 if (!string.IsNullOrEmpty(importExtraction))
                {
                    // Check if target has these markers (some app.modules might combine imports, but let's try)
                    if (ReplaceContentBetweenMarkers(ref fileContent, importStartMarker, importEndMarker, importExtraction))
                    {
                        modified = true;
                         Console.WriteLine($"Updated service imports in {Path.GetFileName(targetFile)}");
                    }
                }

                // Service Providers
                string startMarker = $"// Beginning of provider declarations for {moduleName} Data Services";
                string endMarker = $"// End of provider declarations for {moduleName} Data Services";

                string extraction = GetContentBetweenMarkers(sourceContent, startMarker, endMarker);

                if (!string.IsNullOrEmpty(extraction))
                {
                    if (ReplaceContentBetweenMarkers(ref fileContent, startMarker, endMarker, extraction))
                    {
                        modified = true;
                        Console.WriteLine($"Updated service providers in {Path.GetFileName(targetFile)}");
                    }
                    else
                    {
                        Console.WriteLine($"Warning: Could not find markers '{startMarker}' in {Path.GetFileName(targetFile)}");
                    }
                }
            }
            else
            {
                Console.WriteLine($"Error: Could not find service source list file '{serviceListSource}'");
            }

            if (modified)
            {
                File.WriteAllText(targetFile, fileContent);
            }
        }

        private static void UpdateRoutingFile(string targetFile, string moduleName, string componentListSource, string routesListSource)
        {
            if (!File.Exists(targetFile)) return;

            string fileContent = File.ReadAllText(targetFile);
            bool modified = false;

            //
            // Update Imports (Using routes list file which contains the subset of imports needed)
            //
            if (File.Exists(routesListSource))
            {
                string sourceContent = File.ReadAllText(routesListSource);
                string startMarker = $"// Beginning of imports for {moduleName} Data Components";
                string endMarker = $"// End of imports for {moduleName} Data Components";

                string extraction = GetContentBetweenMarkers(sourceContent, startMarker, endMarker);
                
                if (!string.IsNullOrEmpty(extraction))
                {
                    if (ReplaceContentBetweenMarkers(ref fileContent, startMarker, endMarker, extraction))
                    {
                        modified = true;
                        Console.WriteLine($"Updated imports in {Path.GetFileName(targetFile)}");
                    }
                    else
                    {
                        Console.WriteLine($"Warning: Could not find markers '{startMarker}' in {Path.GetFileName(targetFile)}");
                    }

                }
            }

            //
            // Update Routes
            //
            if (File.Exists(routesListSource))
            {
                string sourceContent = File.ReadAllText(routesListSource);
                string startMarker = $"// Beginning of routes for {moduleName} Data Components";
                string endMarker = $"// End of routes for {moduleName} Data Components";

                string extraction = GetContentBetweenMarkers(sourceContent, startMarker, endMarker);

                if (!string.IsNullOrEmpty(extraction))
                {
                    if (ReplaceContentBetweenMarkers(ref fileContent, startMarker, endMarker, extraction))
                    {
                        modified = true;
                        Console.WriteLine($"Updated routes in {Path.GetFileName(targetFile)}");
                    }
                }
            }

            if (modified)
            {
                File.WriteAllText(targetFile, fileContent);
            }
        }

        private static string GetContentBetweenMarkers(string content, string startMarker, string endMarker)
        {
            int startIndex = content.IndexOf(startMarker);
            int endIndex = content.IndexOf(endMarker);

            if (startIndex == -1 || endIndex == -1 || startIndex >= endIndex)
            {
                return null;
            }

            // Return content inclusive of boundaries? No, strictly between.
            // Using the same logic as replacement target
            
            int contentStart = startIndex + startMarker.Length;
            return content.Substring(contentStart, endIndex - contentStart);
        }

        private static bool ReplaceContentBetweenMarkers(ref string content, string startMarker, string endMarker, string newContent)
        {
            int startIndex = content.IndexOf(startMarker);
            int endIndex = content.IndexOf(endMarker);

            if (startIndex == -1 || endIndex == -1 || startIndex >= endIndex)
            {
                return false;
            }

            // We want to keep the markers, and replace everything in between.
            // The insertion point is after the start marker.
            int insertionStart = startIndex + startMarker.Length;
            
            string pre = content.Substring(0, insertionStart);
            string post = content.Substring(endIndex); // Keeps the end marker

            // Determine indentation of the start marker to align the end marker
            string indentation = "";
            int lineStart = content.LastIndexOf('\n', startIndex);
            if (lineStart != -1)
            {
                indentation = content.Substring(lineStart + 1, startIndex - (lineStart + 1));
            }
            else
            {
                indentation = content.Substring(0, startIndex);
            }

            // Ideal formatting: Newline, Content, Newline, Indentation matching start, End Marker
            content = pre + Environment.NewLine + newContent.Trim() + Environment.NewLine + indentation + post;
            return true;
        }
    }
}
